### ISSUE TITLE
[BaekJoon] 토마토

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/SSAFY_Algorithm#1]
문제링크
https://www.acmicpc.net/problem/7576

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
풀이 사항
풀이 일자: 2024.07.26
풀이 시간: 30분 00초
채점 결과: 정답
예상 문제 유형: BFS

풀이 방법
처음에는 큐에 어떤 익은 토마토 부터 넣어야 하는지 감이 안잡혔으나
모든 익은 토마토를 큐에 넣고 bfs를 진행하여 풀이하였습니다.

**Comment by jongchan0109** [comment]
풀이 사항 
풀이 일자: 2024.07.30 
풀이 시간: 15분 00초 
채점 결과: 정답 
예상 문제 유형: BFS
풀이 방법 
문제의 "토마토가 모두 익을 때까지의 '최소' 날짜를 출력해야 한다."를 읽고, BFS유형이라 생각하여 Queue를 이용하여 풀었습니다. 처음 제출 때, 저장될 때부터 모든 토마토가 익어있는 상태이면 0을 출력해야 한다는 것을 제대로 확인하지 못하여 틀렸었고, 이후 확인한 뒤 정답을 맞췄습니다.

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.07.31
풀이 시간: 10분 00초
채점 결과: 정답
예상 문제 유형: BFS

풀이 방법
토마토가 다 익기까지 필요한 최소 일수를 구하려면 

모든 익지 않은 토마토에 대해 가장 가깝게 위치한 익은 토마토까지의 거리를 구해야한다는 관점으로 BFS를 사용한다.

만약 익은 토마토가 한개라면 미로탐색이랑 비슷하게 시작해서 익은 토마토가 있는곳을 시작점으로 해서 BFS를 시작하면되지만 `시작점이 “여러개”` 이다.

각 익은 토마토들에 대해 해당 위치를 시작점으로 하는 BFS를 한 번 씩 다 돌리는 방법을 떠올릴 수 있지만 , 그러면 BFS의 시간복잡도가  `O(MN)` 이고, 익은토마`토 O(MN)` 으로 시간복잡도가 `O(M^2N^2)`가 될 수 있다. ( 시간으로 해결이 안된다. ) 

해결법은 `그냥 모든 시작점을 큐에 넣고` `앞에서 BFS를 돌면 끝이다.`

**Comment by UnrequiredOne** [comment]
- 풀이 사항
1. 풀이 일자: 2024.07.31
2. 풀이 시간: 30분 00초
3. 채점 결과: 정답
4. 예상 문제 유형: BFS

- 풀이 방법
1. 점점 퍼져가는 형태를 생각해서 BFS에 따른 문제일 것이라고 추측. 큐를 쓰기로 결정함.
2. 다만, 일자에 따른 토마토의 퍼지는 순서에 우선순위가 있을 것이라 생각하여, 일자를 기준으로 우선순위 큐를 사용해야한다 라고 생각하였음.
3. 입력받는 과정에서, 만약 익은 토마토의 위치가 주어진다면 바로 큐에 넣어줬음.
4. 그래서 만약 익은 토마토에서 익은 토마토로 가는 어떤 경계가 있다면, 일자를 갱신해주면 되고, 그것이 답이 될 것이라고 생각함.
5. 만약 BFS가 끝났을때, 안익은 토마토가 있다면 -1을 출력해야한다. 라는 조건에서, 적절한 방법을 생각하지 못해 이중 for문을 돌려 완전히 다 찾는 O(NM)의 형태로 찾았음.

- 피드백 후
1. 우선 순위 큐를 사용하지 않아도, 거진 일자대로 넣어질 것이기에 우선순위 큐가 아니더라도 일반 큐(파이썬 deque)를 사용해도 된다. 라는 생각을 하였음.
2. 마지막에 안익은 토마토가 있는지 검증할때, 이중 for문으로 탐색하는건 비효율임. 
따라서 완전히 퍼졌을때의 토마토의 수(num_of_full_tomato)와 BFS에서 퍼트린 토마토의 수(num_of_gotten_tomato)를 비교했을 때, 다르면 -1을 출력해도 됨.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.01
풀이 시간: 90분 00초
채점 결과: 정답
예상 문제 유형: BFS

풀이 방법
처음에 단순히 while문으로 모든 맵을 탐색하며 토마토를 익히고 더이상 바뀐 부분이 없다면 while문을 빠져나왔는데 당연하게도(?) 시간초과가 발생하였다 그 이후 BFS를 써야한다는 아이디어를 얻고 다시 풀어서 정답을 찾았다. 
1. 코테 문제에서 객체를 사용해 본적이 거의 없었는데 토마토의 좌표와 몇 일 동안 익었는지를 체크해 주기 위해 객체로 생성해주었다.
2. 큐를 이용하여 처음에 1인 부분을 넣어준뒤 BFS에서 탐색을 진행해주었다.
3. 퍼져나갈때마다 날짜를 1증가시키고 가장 최대값을 정답에 지속적으로 넣어주었다.
4. 큐에 모든 원소를 집어 넣고 빠져나왔는데도 불구하고 0인 값이 맵에 존재한다면 -1을 출력해준다.

교훈: 손가는대로 먼저 풀지말고 계획을 세우고 풀자

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.07.29
풀이 시간: 30분 00초 
채점 결과: 정답 
예상 문제 유형: BFS
풀이 방법:
큐에 토마토 위치와 날짜를 넣고 BFS탐색을 돌림
피드백을 해보니 지도 배열에 날짜 정보를 바로 저장하는게 더 효율적일 거 같다.
