### ISSUE TITLE
[BOJ] 정육면체 전개도

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#113]
문제링크
https://www.acmicpc.net/problem/1917

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.31
풀이 시간: 33분
채점 결과: 정답
예상 문제 유형: 구현, dfs

## 풀이 방법
1. 처음에는 모든 주사위의 전개도를 생각해 보려고 했으나, 매우 생각하기 힘들 것 같았음
2. 맵에 직접 주사위를 굴려보기로 결정함
3. boj 주사위 굴리기 문제를 풀 때 처럼 주사위를 구현하여 맵에 굴려봄
4. dice 배열을 각각 0은 밑면, 1은 정면, 2는 윗면, 3은 뒷면, 4는 왼쪽, 5는 오른쪽이라고 가정하고 주사위를 굴림
5. dfs를 이용하여 인접한 모든 1을 방문했을 경우, dice 배열이 모두 채워져 있을 경우 true 리턴

### 느낀점
주사위 굴리기 문제를 풀어보지 않았더라면, 매우 어렵게 느껴졌을 것 같음.

**Comment by UnrequiredOne** [comment]
## 풀이 사항
---
풀이 일자: 2024.09.04
풀이 시간: 90분
채점 결과: 정답
예상 문제 유형: 구현, dfs

## 풀이 방법
---
1. 가능한 전개도 형태를 모두 적어보려고 했으나, 회전이나 뒤집어진 것을 일괄적으로 처리할 자신이 없어서 기각했음.
2. 주사위 굴리기 처럼 직접 굴려보기로 생각함
3. 처음엔 그냥 맵 전체에 다 굴려보면 알아서 만들어지는게 아닐까? 라고 생각했으나 아니었음 => 그래서 전개도의 좌표만 뽑아내서 굴리기로 함
4. 처음엔 재귀 사용없이 스택을 이용한 DFS로 풀 수 있을 거라고 생각했으나, 직접 코드 작성을 하다보니 돌아가야하는 좌표 등 생각 해줘야 할게 많았음. 여기서 시간을 많이 잡아먹음
5. 그래서 재귀를 이용한 DFS로 결정하고 구현하니, 코드 수정없이 순식간에 풀렸음....

## 느낀점
---
지금까지 구현 문제를 풀 때는 설계를 어느정도하고 바로 코드 작성으로 들어갔으나, 앞으로는 좀 더 설계를 치밀하고 정확하게 한 다음 들어가야겠다고 생각함.

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 4시간
채점 결과: 정답
예상 문제 유형: 구현

### 풀이방법
1. 주사위의 6가지 면을 표시하는 변수를 설정한다
2. 전개도 위에서 dfs를 실행하면서 주사위를 회전시키며 바닥과 맞닿는 숫자를 방문체크한다.
3. 만약 모든면이 만났으면 yes 아니면 no

### 느낀점
맵 위로 주사위를 굴리는게 아니라 전개도를 접는 느낌으로 문제를 풀려고 했는데 결국 성공하지 못했다.
멘탈이 나가면 문제 해답 방식을 접근하는데 너무 오래걸리는 거 같다.
시험때는 아예 싹 지우고 다시 생각하는 방식을 사용해야할거같다.

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.09.01
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 구현

### 풀이방법
1. 1로 표시된 첫 위치 찾기
2. DFS 사용해서 모든 1 연결 되어있는지 검증
3. 정육면체가 맞는지 판단

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.05
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 구현, dfs

## 풀이 방법
1. 마지막으로 받은 1의 좌표를 저장해두고 그 좌표부터 dfs를 탐색해준다.
2. map[nr][nc]가 1이고 방문하지 않았다면 dice에 넣어주고 재귀, 빠져나올땐 반대로 돌려준다.
3. dice에서는 방향만을 파라미터로 받고 해당 방향에 따라 주사위를 굴려주고 맨 밑바닥을 1로 바꾼다.
4. dice 배열에 0이 하나라도 있으면 ans -> false : no를 출력해준다.

풀이 방법에 대한 감이 잡히지 않아 주사위를 굴리라는 힌트를 보고 풀었다. 오래 붙잡아도 아이디어가 생각이 안날꺼 같으면 힌트를 좀 보고 푸는것도 나쁘지 않다 생각한다.
