### ISSUE TITLE
[BOJ] 아기 상어

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#114]
문제링크:
https://www.acmicpc.net/problem/16236

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 41분
채점 결과: 정답
예상 문제 유형: 구현, bfs

## 풀이 방법
1. 더 이상 먹을 수 있는 물고기가 없다면 -> BFS로 탐색한 결과 먹을 수 있는 물고기가 없으면 false를 반환해야 하겠다고 생각
2. 먹을 수 있는 물고기가 많다면 -> 가장 가까운 물고기 + 가장 위에 or 가장 왼쪽에 -> bfs인데 현재 시간이 거리이므로, 물고기를 먹는 경우 중 가장 행이 작고, 열이 작은 좌표를 선택해야겠다고 생각함

### 느낀점
설계를 잘 하면 쉽게 풀 수 있는 문제

**Comment by leafeafeaf** [comment]
git commit -m "김성민 / 240903 / [BOJ_아기 상어_16236] / 112ms"
풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: bfs,시뮬레이션

풀이방법
1. 데이터를 입력받는다.
 1-1 상어의 위치와 크기를 따로 전역변수로 저장한다.
2. 상어 현재 위치와 가장 가까우면서도 먹을 수 있는 물고기를 BFS로 탐색한다.
3. 물고기 들중 y가 가장 작고 x가 가장 작은 좌표로 상어를 이동시키고 시간을 더한다.
4. BFS를 성공할때마다 상어가 물고기 먹은 개수를 높이고, 개수에 따라 사이즈를 키운다.
5. BFS함수가 false를 리턴하면 더 이상 먹을게 없으니 현재 시간을 출력한다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 만 2일
채점 결과: 정답
예상 문제 유형: BFS, 시뮬레이션

## 풀이 방법
1. 맵을 입력받으며 상어의 위치를 저장하고 맵의 해당위치를 0으로 초기화한다.
2. 우선순위 큐를 사용했으며 거리, 열, 행 순으로 정렬해주었다. 
3. while문을 돌며 우선순위큐를 비워주고 bfs탐색을 통해 갈 수 있는 위치에 안먹은 물고기가 있고 사이즈가 먹을 수 있는 물고기라면 우선순위 큐에 넣어준다. 
4. 큐에 제일 앞에 있는 원소를 빼주고 해당위치로 상어위치 이동 상황에 따른 상어의 크기 증가를 구현해주었다.

## 회고
1. 거리가 같을때 어떻게 배열을 저장할 지 처음부터 잘 고민하기
2. 시간복잡도를 설계단계에서 고민하기

**Comment by kub938** [comment]
풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 구현, bfs

풀이 방법
1. bfs 사용, size 이용해서 큐에 들어있는만큼 for문 돌려서 해당하는 싸이클에 먹을 수 있는 물고기 배열에 다 넣음
2. 배열에 물고기가 들어가 있을 경우 가장 위, 가장 왼쪽 물고기 선택(sort 해놓음)해서 먹고 현재 좌표에서 다시 bfs를 돌림 (visited 초기화)

회고
---
- 종찬이형이 bfs 재귀로 쓰는사람 처음봤다함
- 변수 너무 난잡함, 줄일수 있는 방법 생각해보기
- 주석 달기
