### ISSUE TITLE
[BOJ] 큐빙

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#115]
문제링크:
https://www.acmicpc.net/problem/5373

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.01
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 처음에는 하나하나 빡구현 할 생각을 하지 못하고, 효율적으로 가능한 방법이 있나 1시간 정도 고민함.
2. 고민 결과 빡구현이 가장 편할 것이라고 생각
3. 큐브의 시점을 고정하고, 0이 윗면, 1이 정면, 2가 오른쪽 면, 3이 뒷면, 4가 왼쪽 면, 5가 밑면 이렇게 하고 각각 회전이 발생할 시 값이 어떻게 변할지 모든 경우 생각해봄
4. 해결

### 느낀점
플래티넘 빡구현 문제는 다르구나...
문제 낸 사람 좀 혼나야 할 듯
