### ISSUE TITLE
[BOJ] 종이접기

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#118]
문제링크:
https://www.acmicpc.net/problem/20187

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.02
풀이 시간: 60분 00초
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 2^k x 2^k 만큼의 map을 만들어주고 마지막에 접는 x축, y축 접는 방법을 기억해 둔다. (예, RD, LU)

2. 각각의 경우에 대해 어느 구역에 구멍을 뚫는지 위치를 저장해준다. 왼쪽 위 부터 뚫는 방법 그대로이다. 

3. 복사할 맵 유형이 4가지인데 아까 뚫었던 구역과 구멍번호가 일치하는 유형을 찾아준다.

4. 맵의 크기만큼 복사해준다.

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.09.03
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 구현

풀이방법
1. 데이터를 입력받는다
2. 구멍의 정보를 저장할 2차원 리스트를 생성하고 처음 값을 저장한다.
3. 명령을 역순으로 실행한다
    3-1 위와 왼쪽은 앞에 데이터를 추가 아래와 오른쪽은 데이터를 뒤에 넣는다.
    3-2 가로인지 세로인지에 따라 숫자를 바꾸는 함수를 실행한다.
4. 완성된 리스트를 출력한다.

느낀점)
완전 구현을 했다. 함수화를 진행한다면 좀 더 원활한 디버깅이 되었을 거 같다.

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.09.04
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 구현

# 풀이 방법
접기 방향에 따라 구멍 위치를 결정
마지막 접기 방향 lastHor 과 lastVer 를 기준으로 구멍 위치 결정
종이의 마지막 상태에 구멍 위치 결정 및 최종 구멍위치 계산

**Comment by UnrequiredOne** [comment]
## 풀이 사항
풀이 일자: 2024.09.05
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
잘 안풀려서 힌트 참고했다.
마지막 접는 방법과 구멍의 위치에 따라 모양새가 바뀌는걸 알고 그에 따라 모양새를 미리 구해놨고, 그걸 복사했다.
