### ISSUE TITLE
[BOJ] 색종이 붙이기

### ISSUE THREAD

**Issue by kub938** [SSAFY12th/SSAFY_Algorithm#140]
문제링크:
https://www.acmicpc.net/problem/17136

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.07
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: 구현, 백트래킹

## 풀이 방법
1. 1이 적힌 점들을 리스틑에 기록한다.
2. 만약 리스트의 사이즈가 0이면 0출력 후 return
3. 1이 적힌 점들을 순회하며 색종이를 붙이는데, 색종이가 큰 것이 유리할 것이라고 생각해서 큰 것 부터 작은 순서대로 붙여봤다.

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.09.05
풀이 시간: 1시간 50분
채점 결과: 정답
예상 문제 유형: 백트래킹

# 풀이 방법
색종이가 큰게 남아있으면 큰 거 부터 붙여보고 안되면 떼는 백트래킹

**Comment by leafeafeaf** [comment]
###풀이 사항
풀이 일자: 2024.09.10
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 중복순열, DFS

### 풀이방법
1. 데이터를 입력받으면서 fletten하게 만들어 리스트에 저장
2. 중복 순열을 사용하여 dfs돌림
    1) 각 색종이 개수가 5개 넘어가면 백트래킹
    2) 최솟값보다 크면 탐색할 필요 없어서 백트래킹
    3) 크기가 5부터 1까지 색종이를 넣을 수 있는지를 확인하고 다음 dfs 호출

### 느낀점
색종이를 넣는지 확인하는 과정이 비효율적이라 시간이 많이 나왔다
다른 방식을 찾아보니 배열 0,0 부터 9,9까지 dfs를 호출하는 방식을 사용하는게 훨씬 효율적인거 같다.

**Comment by UnrequiredOne** [comment]
## 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 5시간
채점 결과: 정답
예상 문제 유형: DFS, 백트래킹

## 풀이 방법
1. DFS를 돌린다.
2. depth가 최대 색종이 수를 넘으면 자르고, 지금까지 찾은 min 색종이 수 넘어가도 자른다.
3. 백트래킹도 해준다
4. 좌표값을 옮긴다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: DFS

## 풀이 방법
1. 맵 전체를 DFS (조합)으로 돌며 1을 만나면 큰 색종이부터 순차적으로 붙일 수 있는지 체크 한 뒤, 붙일 수 있다면 쓴 색종이 수를 늘리고 0으로 채워준다.
2. dfs을 다 돌고 빠져 나왔다면 다시 1로 초기화 해준다. 
3. 색종이를 붙이지 못한다면 어차피 위에서 아래로, 좌측에서 우측으로 순회하며 붙이기 때문에 끝까지 다 돌아도 붙이지 않는 구역이 되버린다. 따라서 더이상 dfs를 들어가거나 맨 마지막에 검사해줄 필요가 없으므로 return 해준다.
4. 맵의 마지막까지 성공적으로 색종이를 붙였다면 맵에 1이 있는지 확인하고 없다면 ans의 최솟값을 갱신해준다.
5. dfs를 들어갈때 만약 정답보다 색종이를 붙인 횟수가 많아졌다면 어차피 정답이 아니므로 백트래킹해준다.
