### ISSUE TITLE
[SWEA] 핀볼 게임

### ISSUE THREAD

**Issue by kub938** [SSAFY12th/SSAFY_Algorithm#142]
문제링크:
[[모의 SW 역량테스트] 핀볼 게임](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AWXRF8s6ezEDFAUo&categoryId=AWXRF8s6ezEDFAUo&categoryType=CODE&problemTitle=%EB%AA%A8%EC%9D%98&orderBy=SUBMIT_COUNT&selectCodeLang=ALL&select-1=&pageSize=10&pageIndex=1)

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
***풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 구현

***풀이방법
1. 데이터를 입력받는다.
 1-1 웜홀을 따로 배열에 저장한다
2. 0인 칸에 상하좌우에 대해서 모두 핀볼 함수를 실행한다.
3. 경로에 부딪힌 블록수(score)를 리턴한다.
    3-1 시작칸, 블랙홀을 만나면 score리턴
    3-2 벽이나 블록에 의해 그대로 반대방향으로 튕겨져나오는 경우, score*2+1을 리턴한다.
4. 이중 최대값을 리턴한다.

***느낀부분
블록 모양에 따라 상하좌우바뀌는 것을 구현하는데 시간이 걸렸다.
어짜피 반대방향으로 튕겨져 나오면 같은 루트를 걸쳐서 재자리로 돌아오는걸 파악하고
score*2+1을 리턴하면 시간을 많이 줄일 수 있다.

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.09.06
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 단순 구현
시간: 2,545 ms
메모리: 113,980 kb

# 풀이 방법
1. 블랙홀 좌표와, 웜홀 좌표를 리스트로 관리
2. 0인 지점에서 상하좌우 모두 핀볼 쏴보고 점수 갱신 !
3. 방향을 고정하고, 블랙홀을 만나거나 초기위치를 만나지 않으면 반복
4. 블록을 만났을경우, 벽을 만났을경우 고려하여 방향 변환
5. 웜홀을 만났을 경우, 같은 웜홀 번호를 갖고있지만 , x y가 다른 웜홀 (이러면 짝 웜홀임) 을 찾아서 그 웜홀로 이동

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.11
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 웜홀 좌표를 Map으로 관리한다.
2. 0인 지점에서 상하좌우 방향 시작으로 탐색 시작한다.
3. 방향이 반대가 되는 경우 cnt값을 구해서 return한다.


## 느낀점
1. 테케가 이상해서 시간이 오래 걸렸다 ㅋㅋ

**Comment by UnrequiredOne** [comment]
## 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 벽돌이 쳐주는 모양을 미리 만들어 놓는다.
2. 웜홀을 hashmap(dict)로 만들어 놓는다.
3. 0인 지점을 모두 저장해놓고 for문을 돌린다.
4. 벽돌을 만날 경우와 벽을 만날 경우 score를 +1한다.

## 느낀점
그냥 무난했던 거 같다

**Comment by kub938** [comment]
풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법
1. block을 타입별로 리스트 만들어서 관리
2. nowDir로 현재 방향 관리
3. 웜홀은 넘버, 좌표값을 넣은 리스트로 관리
4. 완탐 돌면서 0인 지점에서 4방향으로 모두 함수 호출
5. 벽 만날때마다 cnt, 최댓값 출력

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.12
풀이 시간: 90분
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 이중포문으로 맵 전체를 돌며 0인 구역에서 탐색을 진행하고 빠져나온뒤 점수를 계산해 주었다.
2. 사방 외벽에 부딪히는것들을 먼저 계산해 주었고 점수를 늘리고 방향을 바꿔주었다.
3. 블록에 부딪힌다면 현재 진행하고 있는 방향에 따라서 스위치문을 통해 방향을 바꿔주었다. 
4. 웜홀이나 블랙홀을 만난다면 미리 저장해 두었던 배열을 참고해서 위치를 이동시키거나 함수를 종료해준다.
5. 스위치문을 통해 방향을 지정해주는 것보다 이중배열을 만들어서 관리하는것이 훨씬 편하다는것을 알았다.
