### ISSUE TITLE
[SWEA] 보급로

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/SSAFY_Algorithm#156]
## 문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV15QRX6APsCFAYD

## 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

## 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.21
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 구현, BFS

## 풀이 방법
1. bfs를 이용해서 탐색을 하는데, PQ를 이용하여 비용이 낮은 좌표에서 우선적으로 탐색하게 구현하였다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.22
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 다익스트라

## 풀이 방법
1. 이차원 배열을 map, visited, min 세가지를 만들어 주고 오름차순 pq를 만들어준다.
2. min에는 각 맵의 시작점 부터 해당 지점까지 가는 최소 거리를 저장해주고 bfs를 통해 방문하지 않은 노드에 대해서 우선순위 큐에 삽입해준다.
3. 도착점에 도착했다면 해당 지점의 거리를 출력한다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.09.22
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 최단경로탐색

## 풀이 방법
다익스트라 알고리즘으로 우선순위 큐를 활용하여, 비용이 더 적으면 우선이 되게 큐에 넣어 탐색하였다.

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.09.23
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 우선순위큐

### 풀이방법
 1. 데이터를 입력받는다.
 2. 우선순위큐를 사용해서 최단거리를 구한다.
 3. 만약 목적지에 도착했으면 반복을 종료하고 그때 비용을 출력한다.
