### ISSUE TITLE
[BOJ] 도시 분할 계획

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/SSAFY_Algorithm#157]
## 문제 링크
https://www.acmicpc.net/problem/1647

## 풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

## 풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.22
풀이 시간: 21분
채점 결과: 정답
예상 문제 유형: MST

## 풀이 방법
1. 최소신장트리를 만드는데, parent가 2개가 남을 때까지 반복한다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.09.22
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 최소 신장 트리

## 풀이 방법
크루스칼 알고리즘으로 최소 신장 트리를 만들고 가장 가중치가 높은 간선을 마지막에 제거하면
그게 바로 최소비용임을 판단하여 만들었다

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.09.23
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 최소신장트리

### 풀이방법
 1. 데이터를 입력받는다.
 2. mst 크루스칼을 사용하여 n-2개의 간선을 추출하고 모두 더한다,

### 느낀점
처음에 문제에 2개 그룹으로 나눈다에 정신이 팔려서
시간초과를 나지 않고 어떻게 조합을 넣을까라고 생각한 것이 안좋았던거 같다.
함정에 빠지지 않게 잘 문제를 고려해야 할 거 같다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.24
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 최소 신장 트리

## 풀이 방법
1. 인접리스트로 양방향 가중치를 받아준다.
2. prim 알고리즘과 우선순위 큐를 사용하여 MST를 만들고 가중치를 더해준다.
3. 가장 컸던 가중치를 마지막에 빼고 출력해준다.
4. 처음에 인접행렬로 구현했을때 메모리초과가 발생하였다. 입력크기를 잘 확인해서 문제를 풀자.

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.09.26
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: MST

풀이 방법
선택된 경로들의 유지비 중 가장 큰 값을 mc변수에 갱신
MST 구축 후 총 유지비에서 mc 값을 뺌
