### ISSUE TITLE
[BOJ] 학교 탐방하기

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/SSAFY_Algorithm#158]
문제 링크
https://www.acmicpc.net/problem/13418

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.09.22
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 구현, BFS

## 풀이 방법
크루스칼 알고리즘을 두가지버전으로 푼뒤 계산하였다
오르막길을 우선 정렬하는 경우와 내리막길을 우선 정렬하는 방식이 최선과 최악임을 이용하였다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.24
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: MST

## 풀이 방법
1. 최소신장트리, 최대신장트리를 사용해서 풀이하였다.
2. 문제를 잘못읽고 오르막길이면 반대에서는 내리막길이라고 생각해서 이해하는데 오래걸렸다.
3. 오르막길이 1이고 내리막길이 0이라고 생각해서 잘못풀어서 오류가 생겼다.
4. 문제를 잘 읽고 풀자

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.09.26
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: MST

## 풀이 방법
1. 두개의 최대 신장 트리, 최소 신장 트리를 만든다.
2. 크루스칼로

인간적으로 내리막길이 0이어야 하지 않나?
