### ISSUE TITLE
[BOJ] 숨바꼭질 4 

### ISSUE THREAD

**Issue by jongchan0109** [SSAFY12th/SSAFY_Algorithm#177]
문제 링크
https://www.acmicpc.net/problem/13913

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
### 풀이 사항
풀이 일자: 2024.09.27
풀이 시간: 21분
채점 결과: 정답
예상 문제 유형: BFS

### 풀이방법
 1. 시작과 끝을 입력받는다.
 2. BFS를 진행하여 최단 거리를 구한다. (경로의 이전 값을 기록한다)
 3. 최단 시간과 경로를 출력한다

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.09.30
풀이 시간: 2일
채점 결과: 정답
예상 문제 유형: BFS

## 풀이방법
1. 수빈의 위치 N 이 동생의 위치 K 와 같을때, N > K, N <K일때를 각각 나눠서 풀이
2. N > K 일때는 최적해가 계속 N을 1씩 줄여서 K로 가는 방법밬에 없다.
3. N > K 일때 time, before 배열을 만들어 각각 그 위치로 갔을때 걸린 시간과 그 위치로 가기 전의 위치를 저장해준다.
4. q에 먼저 N을 넣어주고 범위를 초과하지 않고, 도착했던 적이 없는 위치 (time[next] == 0)라면 time, before에 값을 저장해주고 그 위치를 큐에 저장해준다.  
5. K에 도착한다면 BFS이므로 가장 먼저 도착했을 때 그 시간이 최적해임이 보장되므로 while문을 빠져나온다.
6. stack을 이용하여 경로를 출력해준다.

## 반성
1. 처음에 방문체크를 before[next]가 0일때를 기준으로 했더니 50퍼에서 메모리 초과가 생겼다.
2. 생각해보니 위치가 그 전의 위치가 0이고 next로 가는 경우 q에서 무한 루프가 생긴다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.10.02
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: BFS

## 풀이방법
1. 동생 위치 찾을때까지 -1 +1 *2 방향으로 너비 우선 탐색
2. 큐에 들어갈때, 부모 숫자와 거리 + 1
3. 동생의 visited값 출력

## 어려웠던점
BFS로 찾는건 되는데 도대체 경로를 어케 저장할지 감이 안왔음
부모를 기록한다는 개념을 알게되었고 출력하는거 어려워서 지피티한테 짜달라했음

**Comment by UnrequiredOne** [comment]
# 풀이 사항
- 풀이 일자: 2024.10.02
- 풀이 시간: 2시간
- 채점 결과: 정답
- 예상 문제 유형: BFS

# 풀이방법
0. 우선순위 큐를 이용하여 t의 횟수를 최소화 시키고자했음.
1. case n < k : n -1 , n + 1, n * 2 너비우선탐색
2. case n > k : for문으로 n-k번 -1 때려서 만든다음에 큐에 넣었음

# 느낀점
1. 처음에 그냥 구현인줄알고 머리 들이밀었다가 그대로 깨짐
2. n > k에선 O(n), n < k에선 O(log n)인줄 알고 가볍게 들어갔다가 머리 깨짐
3. 제발 좀 더 신중하게 살도록 하자.

**Comment by kub938** [comment]
## 풀이 사항

풀이 일자: 2024.10.03
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: BFS
## 풀이방법
1. bfs활용해서 -1,1,*2 각각 진행하는 경우를 모두 진행
2. check에 앞의 좌표값 저장
3. check를 다시 거슬러 올라가며 뒤로 돌리면서 루트 확인
---
## 느낀점
경로를 어떻게 돌아가야되나 모르겠어서 답 찾아보고 구현함
들어간 경로 다 넣고 도착 지점에서 다시 돌아가면 됨
(방문체크 안해서 메모리 초과뜸 레전드레전드)
굳

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: -
풀이 시간: -시간
채점 결과: 정답
예상 문제 유형: BFS

풀이방법
1. bfs로 기록 및 시간 측정  
2. 이전 노드 값을 지정하고 배열에다가 저장한후 역순으로 출력

고민한점 
수빈이의 위치는 항상 0 ~ 100,000의 위치로 고정된다는 보장이없다 .
당연히 음수의 위치로 이동도 할수있고, 십만의 범위 밖으로도 이동이 가능하다 .

하지만 십만의 범위로 이동하게된다면 수빈이의 동생위치를 찾기위해서 -1로만 진행을 할것이기 때문에 사실상 손해다 /
그리고 음수의 위치로 까지 이동하는 것또한 가장 빠른 이동이 될 수없다 / 

그래서 범위가 0 ~ 십만까지가 이상적이다 라는 결론을 했다 .

이런점을 고려하지않고 코딩을 했다면 다른 문제에서 멋대로 가정한것때문에 틀릴 경우도 있을거라 생각했다.
