### ISSUE TITLE
[BOJ] 탑 보기

### ISSUE THREAD

**Issue by jongchan0109** [SSAFY12th/SSAFY_Algorithm#179]
문제 링크
https://www.acmicpc.net/problem/22866

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.02
풀이 시간: 70분
채점 결과: 정답
예상 문제 유형: 메모이제이션, 완탐

### 풀이방법
 1. 데이터를 입력받는다.
 2. 오른쪽 방향으로 재귀를 호출하여 각 타워별 보이는 횟수를 구한다
2-1 타워에서 오른쪽 방향으로 탐색하여 시작타워보다 큰 타워를 찾는다.
2-2 타워에 가장 가까운 타워를 갱신하고 다음 재귀를 호출한다,
2-3 재귀를 빠져나오면서 개수를 1씩 더한다. 1->2->3  2<-1<-0
 3. 왼쪽 방향으로 같은 연산을 진행한다.
 4. 출력한다.

### 느낀점
시간복잡도가 박살이 났다 스택을 활용한 방법을 구상해봐야할거같다.

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.10.03
풀이 시간: 13분
채점 결과: 정답
예상 문제 유형: 자료구조, 스택
시간: 512 ms
메모리: 39792 kb

### 풀이 방법
1. 데이터를 입력 받는다.
2. 왼쪽을 기준으로 탐색을 시작한다.
    2-1. 현재 스택이 비어있지 않고, 스택의 피크에 저장된 인덱스의 높이가 현재 높이보다 클 때까지 스택을 pop한다.
    2-2. 현재 스택의 사이즈를 result[i][0]에 저장하고, 현재 스택의 peek를 result[i][1]에 저장한다.
    2-3. 스택에 현재 인덱스를 push한다.
3. 오른쪽을 기준으로 탐색을 시작한다.
    3-1. 현재 스택이 비어있지 않고, 스택의 피크에 저장된 인덱스의 높이가 현재 높이보다 클 때까지 스택을 pop한다.
    3-2. 현재 스택의 사이즈를 result[i][0]에 더하고, 현재 스택의 peek와 result[i][1]을 비교한다.
    3-3. 스택에 현재 인덱스를 push한다.
4. 결과를 출력한다.

### 느낀점
이런 문제를 풀어야 실력이 빨리 느는 것 같다.

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.10.03
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 자료구조 
### 풀이방법
 1. 현재 인덱스에서 양쪽 방향으로 탐색
 2. 스택에 만나는 건물 삽입
 3. 스택의 탑과 비교하여 같거나 작으면 삽입x
 4. 볼 수 있는 건물 계산

### 느낀점
자료구조 활용을 많이 해봐야겠다는 생각을 했다. 다루는데 어색함이 있었다

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.03
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 스택

## 풀이방법
1. 스택을 사용하여 한칸 움직 일때마다 삽입
2. 나보다 큰 건물이 나올때까지 스택에서 제거
3. 큰건물이 나왔다면 그 이후 건물들도 다 볼 수 있는 건물이기 때문에 스택의 사이즈를 저장
4. 왼쪽과 오른쪽 계산

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.03
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 스택

## 풀이방법
1. 양방향에서 스택써서 넣음
2. 지금 보고있는 건물의 높이보다 peek로 젤 늦게들어간거랑 비교 한다음 같거나 작으면 뺌 -> 높은게 나올 때 까지 진행
3. 차이 계산

## 느낀점
너무어렵고?
