### ISSUE TITLE
[BOJ] 시험 감독

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#194]
문제 링크
https://www.acmicpc.net/problem/13458

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.09.23
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 우선순위큐
시간: 412 ms
메모리: 92272kb

### 풀이방법
 1. 데이터를 입력받는다.
 2. 각 방에 주 감독관을 배치하고 인원을 뺸다
 3. 남은 인원을 부 감독관으로 배치하여 총 개수를 리턴한다.
 
### 느낀점
long타입을 사용해야한다는 것만 파악하면 수월하게 풀 수 있었던 거 같다.
추가적으로 배열로 인원수를 저장하지 않고 문제를 해결한다면 메모리도 아낄 수 있을 거 같다.

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.10.05
풀이 시간: 5분
채점 결과: 정답
예상 문제 유형: 수학
시간: 440 ms
메모리: 92324kb

풀이방법
음...

### 느낀점
음...

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.07
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: 수학

## 풀이방법
주감독관은 무조건 한명 배치한다.
부감독관을 계산할때 정확히 나눠 떨어지면 나눈 몫만, 나머지가 생기면 +1해서 계산해준다.

**Comment by kub938** [comment]
풀이 사항
풀이 일자: 2024.10.07
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 수학

###풀이방법
주 감독관 빼고
부감독관은 주감독관을 뺀 값에서 나눈 값의 나머지가 0이면 패스, 아니면 +1해서 계산

###느낀점
long................................

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.10.08
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 수학

### 풀이방법
 1. 주 감독관은 무조건 한명 있어야 하므로 주 감독관 만큼 카운팅 및 인원수 감소
 2. 부 감독관이 처리 가능한 만큼 나누기
 3. 나머지가 나오면 부 감독관 한명 더 있어야 하므로 + 1
 
### 느낀점
데이터 타입을 신경 쓰자

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.10.08
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 수학

풀이방법

'''
주감독은 반드시 한명 있어야하고, 

부감독은 여러명

주감독을 미리 채워넣고, 
나머지 부감독을 채우기가 정석

주감독이 부감독 보다 값이 더크면 -> 주감독
부감독이 더크거나 같으면 -> 주감독1 + 부감독으로 다채우기

반마다 주감독으로 값을 뺴고 음수면 종료

나머지값을 부감독 값으로 나눈값을 ans에 더하고
나머지값으로 초기화를 시키고, 
0이될때까지 반복.


다른분들은 데이터타입 신경쓴것같다
파이썬은 데이터타입? 댕나줘버려 ㅋ python is king
