### ISSUE TITLE
[BOJ] 로봇 청소기

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#195]
문제 링크
https://www.acmicpc.net/problem/14503

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.06
풀이 시간: 30분 00초
채점 결과: 정답
예상 문제 유형: 구현
시간: 104 ms
메모리: 14356 kb

### 풀이방법
1. 데이터를 입력받는다. (배열크기, 현재 위치 방향, 배열정보)
2. 벽을 만날때 까지 아래를 반복한다.
 2-1 현재 칸이 0이면 청소 1이면 반복 종료
 2-2 주변 4칸 확인
        반시계 방향으로 회전하면서 앞이 빈칸이면 이동
        없으면 후진

### 느낀점

**Comment by jongchan0109** [comment]
### 풀이 사항
풀이 일자: 2024.10.07
풀이 시간: 30분 00초
채점 결과: 정답
예상 문제 유형: 구현
시간: 296 ms
메모리: 21460 kb

### 풀이방법
1. 현재 칸이 0이면 청소
2. 주변 4칸 확인하면서 반복
### 느낀점

**Comment by kub938** [comment]
풀이 사항
풀이 일자: 2024.10.07
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현, bfs
시간: 108 ms

풀이방법
처음칸 청소
사방에 청소할곳 있는지 확인
있으면 90도씩 돌리면서 가장먼저 만나는 청소할 곳으로 진입 -> 다시 처음부터
없으면 후진되나 확인후 안되면 끝 되면 방향 유지하면서 뒤로 빠짐

느낀점
처음에 주어지는 진행방향을 북 서 남 동 순으로 봐서 이거 때문에 30분은 날린듯
문제 확인을 잘하자..

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.10.08
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: BFS 브루트포스 구현

## 풀이 방법
 문제에서 주어진 제한사항을 꼼꼼히 구현하는게 중요한 문제
현재 좌표에서 4방탐색을 한후 청소를 성공했는지 못했는지 여부로 구분하여
후진을 할지 말지 결정하면 된다 나머지는 BFS로 탐색
벽으로 막혀있지 않더라도 맵 구조에따라 전체 청소가 불가능 할 수도 있었습니다.

청소를 성공했는지 여부를 검증하지 않고 BFS탐색을 한다면, 벽에 막혀있지 않는한 
모든 구역을 청소합니다. 또한 BFS문제 이지만 후진 탐색을 진행 할 경우 재귀적 구조를 띕니다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.10
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 구현
시간: 108 ms
메모리: 14408 kb

## 풀이방법
1. 데이터 입력받으면서 청소된 칸을 체크하는 visited배열에 벽인 경우 어차피 들어가지 않을것이므로 청소됐다고 판단하고 1을 넣어주엇다.
2. 문제에서 친절하게 작동 원리를 나눠서 설명해줘서 그냥 그대로 if문을 활용해서 구현했다.
3. 반시계로 회전하는 과정에서 방향을 초기화 해주지 않아서 무한루프가 발생했다. 잘 체크하고 문제풀자.

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.10.09
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현
시간:  36ms


풀이방법
구현의 순서대로 따라갔던거같다

하지만 전의 해설을 보고 풀었던 것처럼 깔끔하게 코드가 떨어지지않지만

혼자 해내서 풀었다는점이 높게 산다.(조금 퇴화한거같아서 슬프기도함)

1. 4칸중 빈칸이 있다면 바로 탐색하는게아니라 반시계로 돈다  (나머지연산으로 처리)
    
    반시계로 돈곳에 청소했다고 “2”로 표시함.
    
    (처음에는 dist 배열이 필요할거같았는데 필요없었음)
    
2. 탐색할 곳이없다면 후진
3. 후진했는데 벽이면 종료

이후 전에 풀었던 코드를 보고 리팩토링 및 재구현을 해봐야겠다.
