### ISSUE TITLE
[BOJ] 낚시왕

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#196]
문제 링크
https://www.acmicpc.net/problem/17143

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
# 풀이 사항
풀이 일자: 2024.10.08
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현
시간: 368 ms

# 풀이방법
1. 낚시King이 상어를 잡는다.
2. 상어를 이동시킨다.
    2-1. 상어를 이동시킬 때 효율적으로 이동시키기 위해 nextX, nextY의 범위에 따라 나눠서 수정시킨다.

# 느낀점
상어를 효율적으로 이동시키지 않아도 해결은 가능하다.
근데 못참겠다...

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.10.08
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 구현 시뮬레이션

# 풀이방법
1. 상어를 클래스로 관리하여 speed, direction, size 데이터를 다루었다.
2. map에 Shark 형 데이터를 담아서 관리
3. 가장 가까운 상어를 잡는다
4. 상어를 이동처리 하였다
5. 같은 자리에 상어가 있으면 크기 비교해서 큰 상어를 덮어 쓰기

# 느낀점
속도가 매우 느린데 효율적인 방법을 찾아 봐야겠다, 근데 풀어 낸 거 자체가 기적이긴 한데

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.10
풀이 시간: 2시간 30분
채점 결과: 정답
예상 문제 유형: 구현
시간: 468 ms
메모리: 32248 kb

### 풀이방법
1. 데이터를 입력받는다. (열 상어 정보를 저장하는 리스트 배열에 상어를 저장한다.)
2. 열 개수 만큼 반복한다.
    2-1 해당 열 리스트에서 가장 위에 있는 상어를 제거하고 사이즈만큼 결과에 더한다
    2-2 상어를 이동시킨다.
    2-3 겹치는 상어를 제거한다.
3. 결과를 출력한다.
  
### 느낀점
코딩하다가 설계 바꾸고 코딩하다가 설계 바꾸고 반복하다가 포기할뻔했다.
처음에 확실하게 설계해서 이런 문제를 없애야할거 같다.
이동 위치를 구하는 것도 굉장히 설계가 오래걸렸다.
수학적으로 연산하는 문제를 많이 풀어서 이러한 부분을 개선해야할거 같다.

**Comment by kub938** [comment]
# 풀이 사항
풀이 일자: 2024.10.10
풀이 시간: 5시간
채점 결과: 정답
예상 문제 유형: 구현 시뮬레이션

# 풀이방법
1. 상어 객체 생성
2. 상어 위치는 맵 따로 생성
3. 상어 잡는건 낚시왕의 위치에서 가장 위에있는 상어 잡음
4. 상어 움직이는건 dir이 상하, 좌우 일때 따로 분류해서 벽을 만나면 방향을 반대로 돌리도록 짬
5. 다 움직인 뒤 같은 자리에 상어가 있으면 사이즈가 큰 상어만 남긴다.

# 느낀점
객체만 써가지고 수식을 짜서 풀어보려 했지만 안됨.
그래서 그냥 상어 객체에 r,c까지 넣어서 안에서 처리하는 방향으로 했지만 시간복잡도가 (NM)^2이 나와서 시간초과뜸
걍 map 써서 품

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.10.10
풀이 시간: x
채점 결과: 틀림
예상 문제 유형: 구현 시뮬레이션

상어의 이동처리 과정에서 맵크기를 초과하면 반대방향으로 되는점.
그리고 한칸씩 이동하면 시간초과가 뜬다...

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.10
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 구현
시간: 532 ms

## 풀이방법
1. 상어 클래스를 생성하고 이 상어들을 관리할 ArrayList와 map을 만든다.
2. map에 해당위치에 상어를 배치시키고 List에도 상어를 넣어준다. 주의할점은 map에서 상어를 잡았을때 리스트에서 상어를 제거해주기위해 같은 레퍼런스를 참조하는 객체를 넣어줘야한다는점이다.
3. 가로로 한칸씩 이동하며 상어를 잡아준뒤 List에서 하나씩 뽑아서 상어를 이동시킨다. 이때 같은 구역에 있는 상어가 있는 경우 크기에 따라 삭제되므로 List에서 뒤부터 뽑아준다.
