### ISSUE TITLE
[BaekJoon] DFS와 BFS

### ISSUE THREAD

**Issue by sangholee235** [SSAFY12th/SSAFY_Algorithm#2]
문제 링크
https://www.acmicpc.net/problem/1260

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
풀이 사항
풀이 일자: 2024.07.29
풀이 시간: 25분 28초
채점 결과: 정답
예상 문제 유형: BFS / DFS

풀이 방법
인접배열, 인접 리스트 두 방식 모두 접근하였고, 인접 배열 방식은 쉽게 풀렸으나
인접 리스트를 초기화하는 과정이 익숙치 않아 시간을 소비했습니다.

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.07.29 
풀이 시간: 10분 00초 
채점 결과: 정답 
예상 문제 유형:  DFS & BFS
풀이 방법 DFS와 BFS를 이용하여 풀었습니다.
처음 DFS에서 출력을 어떻게 할 지 고민하였고, StringBuilder을 이용하여 해결했습니다.

**Comment by UnrequiredOne** [comment]
- 풀이 사항
1. 풀이 일자: 2024.07.29
2. 풀이 시간: 17분 00초
3. 채점 결과: 정답
4. 예상 문제 유형: DFS와 BFS
- 풀이 방법
간략화된 인접 배열 형식(Python dictionary)으로 풀었음.
DFS 부분에서,  root를 제외한 노드의 출력이 뒤집어져 나오는 문제가 있어서 child를 더해줄때 각 children을 deepcopy해서 뒤집은 다음에 stack에 넣어줬음.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.07.26
풀이 시간: 90분
채점 결과: 정답
예상 문제 유형: BFS / DFS

풀이 방법
인접 배열로는 쉽게 이해하고 풀었으나 인접 리스트를 사용하는데 숙련도가 부족해서 오래걸리게 되었다.
다음과 같은 방법으로 풀었다.
코드 짜기 전에 해야할 것

1. 문제 읽기 (깊이)

2. 써야 되는 변수 정리

    2-1. 전역변수, 즉 메인 클라스 내에서 써야하는 변수 인지 class안에서 써야하는 변수인지 체크

    2-2. 메인에서 써야하는 변수는 테스트케이스 별로 초기화가 필요한 변수, static변수는 다른 method에서 사용해야 되는             변수를 선언한다.

3. 코드 짜는 순서 정리

   3-1. 입력
          > n, m, v 입력
          > a : 맵 정보 생력 및 입력
          > visited 생성

   3-2. dfs 호출
            v isited 초기화
            개행
   3-3. bfs 호출

참고 https://dwshin-dev.tistory.com/112

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.07.29
풀이 시간: 10분 00초 
채점 결과: 정답 
예상 문제 유형: DFS & BFS
DFS와 BFS를 통해서 문제 해결 , 중간에 방문배열을 초기화하지 않아서 잠시 지연됨
