### ISSUE TITLE
[BOJ] 2048 (Easy)

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#215]
문제 링크
https://www.acmicpc.net/problem/12100

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.11
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 구현, 자료구조
시간: 320 ms
메모리: 38072 kb

## 풀이 방법
1. dfs 중복 순열을 돌며 방향을 이동시키고 재귀한다.
2. 맵 정보를 파라미터로 넘겨주어서 최대한 복사를 하지 않도록 하였다.
3. 이동할때는 스택과 큐를 사용하여 현재 숫자가 직전과 같을 경우 큐에 두배로 넣어주고 아닌경우는 그냥 큐에 넣어주었다.
4. 마지막엔 큐가 빌때까지 각 방향에 따라 맵에 넣어주었고 그 맵을 반환해준다.

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.10.11
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 완전탐색, 구현

# 풀이방법
1. 5가지 방향을 중복 순열로 완전탐색
2. 5개 방향을 다 돌려본뒤 맵에서 최댓값 구함
3. Block Class에서 merged 변수로 현재 블록이 현재 회차에서 합쳐졌는지로 같은 값이라도 병합 할지 말지 구분함
4. 모든 경우에서 최댓값 갱신하기

# 느낀점
맵을 자유자재로 다룰줄 알아야 한다고 생각한다 아직도 버겁다..

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.10.12
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현, dfs
시간: 256 ms
메모리: 48860 kb

## 풀이 방법
1. dfs를 이용하여 중복순열을 구현한다.
2. dfs의 깊이가 5인 경우 저장된 경로를 따라 보드를 이동시킨다.
3. 보드를 이동시킬 때 위에서 아래 방향으로 움직이는 것만 구현하고, 나머지는 보드를 회전시켜 구현한다.

## 느낀점
max를 구할 때 max = Math.max(getMax(newMap), max)가 아닌
max = getMax(newMap) 이렇게 하여 30분 동안 헤맸다...

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.15
풀이 시간: 1시간반
채점 결과: 정답
예상 문제 유형: 중복순열, 구현
시간: 292 ms
메모리: 35492 kb

### 풀이방법
1. 데이터를 입력받는다.
2. 중복 순열로 방향을 5개를 선정한다.
3. 방향에 따라 숫자를 합친다.
4. 한번 합쳐진 숫자는 다시 안합쳐지도록 추가적인 변수를 스택에 넣는다.
5. 배열에 최댓값을 리턴한다.

### 느낀점
하나의 메소드로 4 방향을 처리하도록 구현하느라 시간이 오래걸렸다.

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.10.15
풀이 시간: 1시간반
채점 결과: 정답
예상 문제 유형: 중복순열, 구현
시간: 292 ms
메모리: 35492 kb

풀이방법
1. 게임판을 상하좌우로 기울이기

2. 5번 기울이는 각각의 방향을 정하기.

5번 기울이는 모든 경우를 테스트한다.

감시에서 CCTV의 방향을 정하는 상황과 같다.

( 2번은 무조건 짤 수 있어야함. )


### 시간복잡도

시간복잡도는 arr의 배열의 길이가 O(N)으로 처리 할 수 있지만  해당 함수는 O(N^2)이다.

바로 idx를 찾는 12번째 연산 때문인데, 

 arr[i]에 대해 tilted[idx] = 0인 idx를 찾기 위해 idx--를 매번 최대 N번씩 해야 하니 시간복잡도는 `O(N^2)`이 된다

실제로 arr 배열에 2가 꽉 차있다면 그 상황에서 이 함수를 실행했을 때 O(N2)의 시간이 필요함을 알 수 있다.


느낀점
아.. idx를 처리해주는 구현방법도 난관이다.

백트래킹 부분을 처리하는 부분인 모든 방향의 조합은 4진법으로 구현 했으나,

해당 합을구하고 처리하는 방법은 난감할정도다. 다시 트라이해야하는 좋은 삼성 문제다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.17
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 중복순열, 구현
시간: 900ms
메모리: 75428kb

## 풀이방법
1. perm()
- 중복순열로 모든 경우의수로 움직여본다
2. move()
- dir에 따라 상하좌우로 움직이는 함수
- 위로 미는것부터 구현, 테스트 해본뒤 다른 방향은 복붙해서 인덱스값만 수정
- 구현
    - 스택 사용
    - 민 방향에서부터 하나씩 스택에 집어넣으면서 스택안에 같은 값이 있는지 체크, 같을경우 check 확인후 합친값을 스택에 집어넣음.
    - 한번 합쳐진 숫자의 경우 check변수를 이용해서 다른 블럭의 움직임이 있기 전까지 합쳐지지 않게 구현.
    - 스택에 집어 넣어놨던거 map에다 다시 적용
    - 끝나고 젤 큰거 체크
## 느낀점
map을 중복순열 한개 돌릴때마다 초기화 안해서 좀 걸렸다 신경써야될듯
