### ISSUE TITLE
[BOJ] 미확인 도착지

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#216]
문제 링크
https://www.acmicpc.net/problem/9370

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by sangholee235** [comment]
# 풀이 사항
풀이 일자: 2024.10.11
풀이 시간: 1시간 50분
채점 결과: 정답
예상 문제 유형: 최단 경로 탐색

# 풀이방법
1. 그래프 정보를 담을때 모든 그래프의 가중치 2배를 해준다
2. g-h 혹은 h-g를 연결하는 간선 일 경우 -1을 해준다
3. 같은 가중치라서 g-h 간선이 선택되지 않는 경우를 없앰
4. 최종 목적지의 거리가 홀수면 g-h 간선이 선택됐음이 자명

# 느낀점
check변수로 g-h를 선택됐는지 체크했는데 16퍼에서 걸렸음
최단경로는 여러개 일 수 있는데 같은 가중치로 인해 선택되지 않는 경우를
고려하지 못했음 가중치를 조작하는 스킬을 배웠음

**Comment by jongchan0109** [comment]
# 풀이 사항
풀이 일자: 2024.10.13
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 다익스트라

# 풀이방법
1. s에서 다익스트라를 사용하여 모든 정점까지의 최단 거리를 구한다.
2. g에서 다익스트라를 사용하여 모든 정점까지의 최단 거리를 구한다.
3. h에서 다익스트라를 사용하여 모든 정점까지의 최단 거리를 구한다.
4. s에서 목적지 d로 가는 최단 거리 = s에서 g로 가는 거리 + g에서 h로 가는 거리 + h에서 d로 가는 거리 || s에서 h로 가는 거리 + h에서 g로 가는 거리 + g에서 d로 가는 거리이면 d 를 출력한다.

# 느낀점
오랜만에 다익스트라를 하니 헷갈렸다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.16
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 다익스트라
시간: 2548 ms
메모리: 204792 kb

## 풀이방법
다익스트라로 최단경로를 구하고 S -K 를 지나는 경로 중 G - H 를 지나는 길과 H - G 를 지나는 길을 구해서 둘중에 하나라도 최단경로와 값이 같다면 출력해주었다.

## 느낀점
플로이드 워샬로 풀면 시간초과난다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.11
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: 다익스트라

## 풀이방법
그래프 정보를 담을때 모든 그래프의 가중치 2배를 해준다
g-h 혹은 h-g를 연결하는 간선 일 경우 -1을 해준다
같은 가중치라서 g-h 간선이 선택되지 않는 경우를 없앰
최종 목적지의 거리가 홀수면 g-h 간선이 선택됐음이 자명

## 느낀점
좋았다 상호야~
