### ISSUE TITLE
[BOJ] 문자열 폭발

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#217]
문제 링크
https://www.acmicpc.net/problem/9935

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
# 풀이 사항
풀이 일자: 2024.10.13
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: KMP

# 풀이방법
1. pattern을 입력받아 실패함수를 만든다.
2. KMP 알고리즘을 이용해 문자열 매칭 여부를 확인한다.
3. 문자열이 매칭된 경우 없앤다.

# 느낀점
KMP 알고리즘 더 공부해야겠다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.11
풀이 시간: 4시간
채점 결과: 정답
예상 문제 유형: 문자열

## 풀이방법
stack, Char객체이용
완탐을 돌리면서 target에 해당하는 글자가 나오면 pointer(target의 idx)를 한개씩 올리며 진행
target.charAt(point)의 글자가 현재 진행하는 글자와 같으면 현재 char값과 point 값을 스택에 add, 아니면 point값을 0으로 해서 add
point 값이 target의 길이와 같아지면 모두 일치하는것이므로 target 길이만큼 pop진행
모든 pop진행 후 바로 위의 idx의 point값이 0이 아니면 그에 해당하는 point값으로 초기화 한 뒤 다시 2번 진행

## 느낀점
- 설계를 좀더 꼼꼼히 해보자
- 문자열이 길때는 stringBuilder를 사용해서 출력하자..
- kmp 써서 한번 더 풀어봐야겠다

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.13
풀이 시간: 1시간 반
채점 결과: 정답
예상 문제 유형: 스택
시간: 420 ms
메모리: 35728 kb

### 풀이방법
1. 데이터를 입력받는다. (문자열, 비교 패턴)
2. 원본 문자열의 문자 하나씩 스택에 넣는다.
3. 스택의 문자 개수가 비교 패턴과 같거나 크면 비교를 시작한다.
4. 비교 패턴과 같다면 스택에서 그만큼 빼낸다.
5. 모두 끝마치고 스택이 비어있으면 실패 남아있으면 출력

### 느낀점
초반에 스택과 어레이리스트가 기능이 비슷하다고 생각하여 ArrayList로 구현했는데 메모리초과가 발생했다.
스택이 메모리를 덜 사용한다는 것을 알 수 있었다.

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.10.14
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: stack

### 풀이방법
1. 문자열을 하나 하나 탐색하면서 스택에 넣기
2. 스택사이즈가 폭탄 문자열의 크기를 넘으면 폭탄사이즈만큼 뒤로 한글자씩 확인
3. 모든 글자가 같으면 스택에서 사이즈만큼 pop
4. 스택에 쌓인 글자 출력

### 느낀점
문자열을 자바로 다루는게 어색함이 있다 
익숙해져야겠다.

**Comment by PyeonMinjun** [comment]
.
