### ISSUE TITLE
[BOJ] ⚾ 

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#234]
문제 링크
https://www.acmicpc.net/problem/17281

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.18
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: DFS, 구현
시간: 580 ms
메모리: 80520kb

## 풀이 방법
1. 중복 순열을 이용하여 타순을 설정한다. 이때 4번째 타순인 경우엔 반드시 1번타자가 들어가야 하므로 바로 재귀해준뒤 for문을 빠져나간다.
2. 매 이닝마다 while문을 돌며 점수를 계산한다. 이닝이 교체될때 타순이 항상 0번부터 시작되지 않고 바로 전 이닝 타자부터 시작하므로 타자번호를 for문 밬에서 관리해준다.

**Comment by PyeonMinjun** [comment]
풀이 일자: 2024.10.21
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: DFS, 구현


풀이 방법
순열, 그리고 구현으로 배열을 구하고 

해결포인트가 각 타순 3개배열을 만들고 그배열을 구현만해줬다.
처음에는 이걸 풀려니까 각 타순을 배열로 만들어서 pop popleft 이렇게 어렵게 귀찮게 까지 생각까지 했다 풀어보면서 구현실력이 많이 부족하다고 깨달았다. 
그리고

2차원배열을 만들어서 작성하면 시간초과로 통과가 안된다 ..
```
     # for i in range(n):
        for en in ening:
```
각 이닝에 대한정보를 1차원으로 저장해서 나타내야 통과가 된다..
~~파이썬 하지말자  자바는 괜찮은가 ?~~

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 31분
채점 결과: 정답
예상 문제 유형: 순열, 구현
시간: 596ms
메모리: 83704kb

## 풀이 방법
1. nextPermutation을 이용해 순열을 구한다.
2. 4번째 원소가 0인 경우(1번 선수가 4번 타자인 경우) 계산한다.
3. idx를 이용해 타선을 관리하고, 결과를 구한다.


## 느낀점
1. 1번 선수가 4번 타자라는 조건을 제대로 확인하지 못해 시간이 걸렸다.
2. 순서를 구하는 과정에서 1번 선수가 4번 타자로 고정이니 관련해서 시간을 줄일 수 있을 것 같다.

**Comment by UnrequiredOne** [comment]
## 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 100분
채점 결과: 정답
예상 문제 유형: 중복순열
시간: 660 ms
메모리: 110740kb

## 풀이 방법
1. 순열 때린다. 그리고 0번을 4번자리에 삽입한다.
2. 야구하듯이 그냥 계산한다.
3. 매 순열마다 스코어 계산한다.

## 느낀점
배열을 만드는 건 시간적 손해가 크다. 변수는 바로 접근이 가능한 것이니 컨트롤만 할 수 있으면 이쪽을 쓰자.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 3시간 가량.
채점 결과: 정답
예상 문제 유형: 완전탐색, 시뮬레이션
시간: 504 ms

## 풀이 방법
1. 4번타자 고정 후 순열로 배팅오더 작성
2. 배팅오더 고정 된 걸로 야구 시뮬레이션

## 느낀감정
"화"

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 순열, 구현

## 풀이 방법
재귀를 이용해 순열을 구한다.
순열구한뒤에 4번타자가 첫번째 선수인것만 사용
playerIdx으로 타자관리,
3아웃 되면 inning +1
heat점수에 따른 base배열 관리

느낀점
remove 사용한곳을 다 배열로 다시 변환시켜서 재구현 하느라 시간이 너무 오래걸렸다
remove같은건 쓰지말아야겠다...

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.24
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: np, 구현
시간: 588 ms
메모리: 21824 kb

### 풀이방법
1. 데이터를 입력받고 순열을 저장할 배열(0번제외)과 타석 순서를 저장할 리스트를 생성한다.
2. 생성된 순열을 리스트에 넣고 0을 3인덱스(4번 타자)에 삽입한다.
3. 리스트 순서대로 이닝을 진행하여 점수를 구하고 최댓값을 갱신한다.
4. next permutation으로 다음 순열을 구하고 2번으로 돌아간다.

### 느낀점
np에 구현에 미숙한 점이 있다는 걸 알아서 좋았다.
이닝이 끝나면 모든 주자를 초기화해야한다는 걸 잊어서 잠깐 시간이 지연되었다.
