### ISSUE TITLE
[BOJ]불!

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#235]
문제 링크
https://www.acmicpc.net/problem/4179

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.10.18
풀이 시간: 60분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: BFS

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

"""
BFS를 진행하면서 해당  지훈이와 불을 둘 다 진행한다.
그 후 보드판의 입력값을 비교하여 지훈이가 지나갈 수 있는지 없는지 판단을 한다.
지훈이가 보드판에 끝부분에 도달 했다면 시간을 출력한다. 
+1 을해서 진행해주면 될거같다. 

도착하지 못하는 경우는 지훈이가 BFS를 돌며 불보다 값이 작으면서 보드 판끝까지 못가면 불가능을 출력하자.

fix : 
1) 각 큐를 다른것을 써야하나 ? 
 : 큐를 뺄때까지 다 진행하므로 상관없다.
    : 생각해보니 처음부터 한 q에 넣으면 처음 좌표를 찾을때 두번 board를 돌아야한다. 
    그냥 큐 두개 만드는게 더 좋을듯

2) 불먼저 BFS를 돌면서 확인하자.

3) 
3 4
###F
.J#.
###.
'''
이 조건에서 불의 dist값은 0이라 지훈이의 값도 0이여서 지훈이가 불 보다 늦은것으로 판단되는 예외처리가 문제 있을 수 있다.
"""

생각보다 예외 케이스가 존재한다... 잘 설계해보자 . 디버깅도 실력도 많이 늘어서 생각보다 헤메진 않았다 .

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.21
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: bfs
시간: 552 ms
메모리: 54132 kb

### 풀이방법
1. 데이터를 입력받으면서 사람과 불을 큐에 넣는다.
2. bfs를 돌리면서 불은 4방향 사람은 그중 한방향으로 이동한다.
3. 끝에 도착하면 리턴

### 느낀점

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: bfs, 구현
시간: 540 ms
메모리: 71984 kb

풀이방법
1. 데이터를 입력받으면서 사람은 배열에 불은 리스트에 넣는다. (성민 풀이방법을 보니 어차피 큐에 넣을건데 먼저 큐에 넣는게 더 효율적일꺼같다.)
2. bfs 탐색을 하는데 1초마다 움직이는 거리와 불이 번지는 거리가 있으므로 qsize를 먼저 계산해 주고 그만큼만 반복한다.
3. 불이 먼저 번지고 사람이 움직여야 한다. 왜냐하면 다음 사람이 이동하는 큐에 넣을 때 그 자리를 가지 않아야 하기 때문이다. (불이 나중에 번지면 사람이도착하고 불길에 휩싸이는 경우다.)

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 21분
채점 결과: 정답
예상 문제 유형: bfs
시간: 576 ms
메모리: 70504 kb

### 풀이방법
1. bfs를 탐색하기전, 사람은 사람 큐에, 불은 불 큐에 넣는다.
2. 먼저 불을 퍼트린다. (fire의 size를 구해서)
3. 사람을 이동시킨다.

### 느낀점
문제에 사람을 먼저 이동시켜야 하는지, 불을 먼저 이동시키는지 명확히 나와있지 않아서 당연하게 사람 먼저 이동시켰는데, 동시에 이동시켜야하는 문제였다...

**Comment by UnrequiredOne** [comment]
### 풀이 사항
풀이 일자: 2024.10.23
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: bfs
시간: 640 ms
메모리: 163956 kb

### 풀이방법
1. 데이터를 입력받으면서 사람의 좌표를 찾고 불의 좌표를 리스트에 넣는다.
2. prev_time과 time을 두고, 시간이 진행되면(prev_time != time) 불을 퍼뜨린다. 시간과 좌표를 우선순위 큐에 넣는다.
3. 리스트를 돌면서 불은 4방향으로 진행, 그걸 담으면 그건 새로운 불의 좌표의 리스트가 된다. 
4. 사람은 4방향 중 한방향으로 이동한다. 근데 불 퍼진 순간 거기에 사람 서있으면 우선순위 큐에서 빼야댐.
6. 끝에 도착하면 탈출시간까지 더해줘서 출력. 큐 다 돌아도 answer가 갱신 안되면 IMPOSSIBLE

### 느낀점
필요한거는 다 작성했는데 순서 배치를 진짜 더럽게 못한다.
코드 순서만 바꿔서 통과해서 혈압오름

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 1시간 20분
채점 결과: 정답
예상 문제 유형: bfs

### 풀이방법
1. 불과 사람의 좌표를 받아서 각자의 큐에 넣음
2. 불을 먼저 bfs탐색
3. 그리고 사람이 가는데 불있는데 가면 안됨 거리 기록
4. 사람이 못빠져나오면 실패
### 느낀점
bfs 각자 돌아가는건 알았는데 실시간으로 같이 어떻게 돌릴지 고민을 많이함.

**Comment by kub938** [comment]
풀이 사항
풀이 일자: 2024.10.24
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: bfs


풀이방법
1. 불, 사람 큐에 넣고 못가는데는 dis에 #으로 처리, 사람위치는 시간 재기위해서 1로 변경
2. 불먼저 탐색하기위해 appendleft를 이용해 맨 처음 위치에 삽입
3. bfs돌림
4. escape함수로 영역밖으로 나가는게 J이면 그 위치값 넣고 return
5. 아니면 impossible 출력

느낀점
good~
