### ISSUE TITLE
[BOJ] Z

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#236]
문제 링크
https://www.acmicpc.net/problem/1074

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by UnrequiredOne** [comment]
### 풀이 사항
풀이 일자: 2024.10.21
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 수학?, 반복문?, Divide and Conquer?
시간: 92 ms

### 풀이방법
표를 쭉 그려보니까 4개씩 묶이고, 반복되는 형태였음.
시점을 옮기거나, 그 4개짜리 표를 땡기는걸 생각을 했는데, 땡기는게 더 좋은거같아서 그렇게 했음 
그래서 어느 사분면에 속해있느냐에 따라 값을 처리해주기로 함
### 느낀점
뭔가 무식하게 푼거같아서 좀 찝찝하긴 한데 나중에 다른 사람 풀이 좀 봐야겠다.

**Comment by jongchan0109** [comment]
### 풀이 사항
풀이 일자: 2024.10.22
풀이 시간: 34분
채점 결과: 정답
예상 문제 유형: 수학, 재귀
시간: 104ms

### 풀이방법
1. 좌표마다 정해진 값이 있을 것이라고 생각함
2. 큰 정사각형을 4개의 사각형으로 나누어 해당하는 위치에 속한 경우로 나눠 계산함
3. 1사분면에 있을 경우 사각형 1개의 사이즈를 더함
    - 2사분면에 있을 경우 더하지 않음
    - 3사분면에 있을 경우 2개의 사이즈를 더함
    - 4사분면에 있을 경우 3개의 사이즈를 더함
4. size가 1일 때까지 즉, 1개의 원소가 선택될 때까지 반복

**Comment by dwshin-dev** [comment]
## 풀이사항
풀이 일자: 2024.10.23
풀이 시간: 30분 + 30초
채점 결과: 정답
예상 문제 유형: 분할정복
시간: 108ms

## 풀이방법
1. 맵을 4등분 하고 1사분면, 2사분면, 3사분면, 4사분면이라 생각을 한다.
2. 각각의 사분면에 좌표가 위치해 있는 케이스마다 각각의 값을 ans의 더해준다.
3. 또한 각각의 사분면에서 다시 작은값으로 재귀해야되기 때문에 R, C값을 조정해준다.

30분 고민해서 안풀려서 다음날 봤는데 30초만에 풀었다.

**Comment by sangholee235** [comment]
### 풀이 사항
풀이 일자: 2024.10.23
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 재귀?


### 풀이방법
1. 현재 좌표의 사분면 파악
2. 사분면을 기준으로 숫자 더해주고 재귀
3. N이 0이 되면 종료
### 느낀점
아이디어 못찾아서 결국 힌트 받고 했다. 어케 풀지 이걸

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.24
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 재귀
시간: 104 ms
메모리: 14352 kb

### 풀이방법
1. 데이터를 입력받는다.
2. 예시를 바탕으로 패턴을 파악한다.
//35 3사분면 + 1사분면 + 4사분면
//32 + 0 + 3 = 35
// 40 -> 3사분면(32) + 3사분면(8) + 1사분면(0) = 40
3. 중앙R과 중앙C를 구하고 이를 각각 비교해보며 몇사분면인지 분류한다.
4. 사분면에 따라 크기에 맞는 값을 더해주고 다음 재귀를 호출한다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.24
풀이 시간: 300분
채점 결과: 정답
예상 문제 유형: 재귀

## 풀이방법
4사분면 쪼개서 각각 r,c가 어디에 속하는지 체크
각각의 면에 대해서 처리 후 재귀

## 느낀점
처음에 0 1 2 3 각각 *4 
때린다음 delta Z자로 가게 설정해놓고 for문 돌려서 value올리고 좌표도 셋팅 하면서 각각 다시 dfs 돌려서 확장시키려 했지만 실패
dfs 넘 어렵구
