### ISSUE TITLE
[BaekJoon] 주사위 굴리기

### ISSUE THREAD

**Issue by jongchan0109** [SSAFY12th/SSAFY_Algorithm#24]
링크: https://www.acmicpc.net/problem/14499

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.07.31
풀이 시간: 120분 00초
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법
위,동쪽,북쪽을 가리키는 방향을 저장하고 주사위 굴리는 방향에 따라 업데이트하였다.
문제 조건을 제대로 파악하지 못해 시간이 오래 걸렸다.
앞으로 문제를 꼼꼼하게 읽으면서 이런 실수를 반복하지 말아야 할 거 같다.

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.08.03
풀이 시간: 50분 00초
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법
주사위 배열을 1차원으로 하여 문제를 풀 수도 있지만, 문제에 나타나 있는 그림을 활용하기 위해 4X3 2차원 배열로 선언하여 문제를 해결하였다.
주사위를 머리속으로 그려보고, 동, 서 , 남, 북 으로 이동시 각각의 면이 어디에서 어디로 이동하는지 생각하면 문제를 해결하는데 용이한 것 같다. 문제의 구현의 난이도는 낮은편이라고 생각한다.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 90분 00초
채점 결과: 정답
예상 문제 유형: 구현

풀이 방법
주사위를 구현하는데 너무 복잡하게 생각한 나머지 구현하는데 실패하고 다른사람의 코드를 보고 풀었다. 그 뒤에는 쉽게 풀렸지만 xy를 혼동하여 또 시간을 오래 쓰고 말았다. 나만의 rc를 만들어서 헷갈림 없이 맵에 xy를 확실하게 구현하자.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.02
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1.  커맨드에 따라 자연스럽게 주사위가 움직이도록 dx dy를 설정했다 
dx = {0, 0, 0, -1, 1};
dy = {0, 1, -1, 0, 0};
2. 커맨드를 리스트로 입력받은뒤 foreach로 순회하였다
3. 주사위를 굴릴때 clone함수를 통하여 복사한뒤 주사위 상태를 옮겼다.

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.07
풀이 시간: 55분
채점 결과: 정답
예상 문제 유형: 구현

- 풀이 방법
개인적으로 이번 주차 중 가장 재미있는 문제였다고 생각함.

처음 문제를 이해하는데 꽤 시간을 투자했음.
주사위가 동서, 북남 별로, 주어진 전개도에서의 움직임이 정 반대인것을 손으로 그려서 확인함.
Python의 Dict를 사용하여 top, bottom, N, S, E, W로 접근케 하였음.

다만 주어진 case에서는 모두 맞았지만 제출땐 바로 틀려서 의아했는데, 코드를 살펴보니 N M을 좀 모호하게 사용하였던 걸 발견함.
초기 좌표에서 x y를 서로 스왑해서 정답은 되었으나, 문제를 읽을 때, 조심해서 읽어야 할 것임.

**Comment by kub938** [comment]
## 풀이 사항

풀이 일자: 2024.08.08
풀이 시간: 3시간
채점 결과: 정답
예상 문제 유형: 구현

---

## 풀이 방법
1. 주사위 면의 위치 값을 [0,1,2,3,4,5] 로 가정
2. 주사위를 동 서 남 북으로 돌려본뒤 인덱스의 변화를 turn_pos의 key값에 해당하는 value값으로 각각 저장
3. key값에 move의 값을 줘서 주사위를 굴림
 
---

## 예상치 못한 오류
- move의 값을 받아 주사위를 굴리는 과정을 반복문을 6번 돌려 각각의 인덱스 값을 조정 했지만 이 과정에서 이미 변경된 값을 다시 가져와 잘못된 값을 넣는 경우가 있었음
-> dice[index] = dice[turn_pos[move][index]] 형식으로 모두 동시에 해당하는 값으로 바꾸는 방법으로 해결
