### ISSUE TITLE
[CT] 정육면체 한번 더 굴리기

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#247]
문제 링크
https://www.codetree.ai/training-field/frequent-problems/problems/cube-rounding-again/

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.24
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 구현, bfs
시간: 123 ms
메모리: 10 MB

### 풀이방법
1. 데이터를 입력받는다.
2. 미리 칸에 도착했을때 얻을 수 있는 점수를 계산한다.(인접한 칸을 찾는 BFS + 인접한 칸에 값을 집어넣는 BFS)
3. 주사위 아래 남쪽 동쪽을 배열로 관리한다. (클래스로 빼는게 더 가독성이 좋을 듯)
4. m번 만큼 주사위를 움직이고 점수를 더한다.

### 느낀점
주사위를 굴릴 때마다 점수를 얻기 위해 bfs를 돌리는건 손해라고 생각하여 미리 bfs를 돌아서 전부 구해서 사용했는데
오히려 속도가 차이가 나지 않았고 오히려 더 느리기도 하였다. 왜 그런지 곰곰히 생각해봐야할거 같다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.29
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: dfs, 구현
시간: 99 ms
메모리: 8 MB

## 풀이방법
1. 데이터 입력받는다.
2. 인접된 같은 숫자에 대한 점수를 기록하는 smap을 dfs를 이용하여 미리 계산해둔다.
3. 주사위를 M만큼 굴리면서 점수를 얻는다.
4. 굴릴 때 마다 주사위 눈을 바꿔주고 방향도 바꿔준다.

**Comment by kub938** [comment]
풀이 일자: 2024.10.29
풀이 시간: 1시간 20분
채점 결과: 정답
예상 문제 유형: bfs, 구현
시간: 138 ms
메모리: 12 MB

풀이방법
1. 주사위를 방향에 따라 돌릴 때 마다 index가 어떻게 변화하는지 구해서 turn 배열에 저장
2. dice 값 배열 만듬 -> 나는 2번 인덱스를 바닥으로 지정하고 만듬
3. 조건에 맞춰서 dir를 변화시키며 주사위 굴림
4. 굴릴때마다 bfs돌려서 점수 받음

**Comment by jongchan0109** [comment]
### 풀이 사항
풀이 일자: 2024.10.30
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 구현, bfs
시간: 134 ms
메모리: 12 MB

### 풀이방법
1. 데이터를 입력받는다.
2. 0,0 에서 시작하여 정육면체를 굴린다.
3. 조건에 맞춰서 방향을 바꾼다.
4. 굴린 후에 bfs를 사용하여 점수를 계산한다.

### 느낀점
1. 문제 초기 조건에 대한 설명이 부족했다. 그림만 보고 유추하라는 느낌을 받았다.
2. 그림만 보고 범위에 벗어나는 경우를 유추했는데, 주사위 그대로 움직이는줄 알았다.
### 코드트리 안푼다.

**Comment by sangholee235** [comment]
### 풀이사항
풀이일자: 241030
풀이시간: 1시간
채점결과: 정답
예상문제유형: 구현

### 풀이방법
1. 주사위의 현재 위치에서 바닥에 BFS를 돌려 점수를 쌓는다
2. 문제의 요구사항에 따라 주사위를 굴린다.
3. 굴린 자리에서 점수를 쌓는다.
 
### 복기
clone 안써서 왜 안구르냐고 화냈다 혼자.
N x M으로 두고 풀어서 안된다고 화냈다.
배운게 많다

**Comment by UnrequiredOne** [comment]
### 풀이 사항
풀이 일자: 2024.10.31
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 구현, bfs
시간: 216ms
메모리: 27MB

### 풀이방법
1. 데이터를 입력받는다.
2. BFS를 이용. 점수를 얻는다.
3. m번 만큼 주사위를 움직이고 점수를 더한다.

### 느낀점
뭔가 서순을 항상 잘못해서 구현에서 코드만 재배열해도 풀림 -> 이거 설계문제겠지
