### ISSUE TITLE
[BOJ] 근손실

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#248]
문제 링크
https://www.acmicpc.net/problem/18429

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
### 풀이 사항
풀이 일자: 2024.10.25
풀이 시간: 15분
채점 결과: 정답
예상 문제 유형: 순열 백트래킹
시간: 120 ms
메모리: 14180 kb

### 풀이방법
1. 데이터를 입력받는다.
2. 순열을 돈다
3. 500이하로 내려가는 선택지가 나오면 백트래킹
4. 끝까지 간 순열 리턴

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.25
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 순열, 백트래킹
시간: 116 ms
메모리: 14204 kb

## 풀이방법
두가지 풀이방법을 이용해서 풀이해봤다.
1. 운동 키트 사용 순서를 순열을 이용해서 끝까지 구한 다음에 운동하고 500이하로 내려가면 바로 리턴, 끝까지 500이하로 내려간적이 없다면 정답 증가
2. 똑같이 dfs 순열을 이용하긴 하지만, 운동 키트 순서를 정할때 마다 계산해서 500이하로 내려간다면 다음 dfs로 들어가지 않게 해주었다. 500이하로 내려가지 않는다면 파라미터로 현재 weight값을 넘겨주어 재귀해주었다.
3. 시간차이가 많이 날꺼라 기대했지만 똑같았다. visited방문 배열을 언제 초기화 해주어야 하는지 아직도 햇갈린다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.10.2
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 순열
시간: 143 ms

## 풀이방법
데이터를 입력받는다.
순열을 돌려서 해당하는 값을 한개씩 더해봄
500이하로 내려가면 false 리턴
안내려가면 true 리턴 cnt+1

**Comment by jongchan0109** [comment]
### 풀이 사항
풀이 일자: 2024.10.30
풀이 시간: 13분
채점 결과: 정답
예상 문제 유형: 순열, np
시간: 120 ms
메모리: 14376 kb

### 풀이방법
1. 데이터를 입력 받는다.
2. nextPermutation을 사용하여 순열을 만든다.
3. 배열을 반목문을 순회하며 합에 현재 인덱스의 값을 더하고 k를 빼며 그 값이 0 미만이면 false를 반환한다.

### 느낀점
nextPermutation을 연습할 겸 풀어봤는데, 아직 헷갈리는 것 같다.
출제자의 의도가 보이는 문제이다.

**Comment by sangholee235** [comment]
### 풀이사항
풀이일자: 241029
풀이시간: 30분
채점결과: 정답
예상문제유형: 순열 완전탐색


### 풀이방법
1. 순열로 운동 키트 순서를 고른다.
2. 시뮬레이션을 통해 통과 여부를 판단하고 answer++을 해준다.
3. answer를 출력한다.
 
### 복기
순열 뽑는걸 아직도 어색해 한다 ㅋㅋ 레전드 ㅋㅋ

**Comment by UnrequiredOne** [comment]
### 풀이사항
풀이일자: 24. 10. 31.
풀이시간: 15분
채점결과: 정답
예상문제유형: 순열 완전탐색


### 풀이방법
1. 순열 돌린다.
2. 그냥 무식하게 하루에 하나씩 적용하고 검사한다
3. answer를 출력한다.
 
### 느낀점
그저 파이썬 딸깍
