### ISSUE TITLE
[PGS] 지형이동

### ISSUE THREAD

**Issue by UnrequiredOne** [SSAFY12th/SSAFY_Algorithm#249]
문제 링크
https://school.programmers.co.kr/learn/courses/30/lessons/62050

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.10.30
풀이 시간: 27분
채점 결과: 정답
예상 문제 유형: 백트래킹, 최소신장트리
시간: 112.59ms (최악)
메모리: 106MB (최악)

112.59ms

## 풀이방법
1. 모든 지형에 대해 상하좌우로 간선을 구한다 (from, to, weight)
    - 간선을 구하는 과정에서 중복을 줄이기 위해 visit 체크를 한다. ( a - > b 와 b -> a 를 같다고 취급)
    - 높이가 height 이하인 경우 weight: 0 아닌 경우 diff
2. 간선을 우선순위 큐에 넣는다.
3. 우선순위 큐를 기준으로 크루스칼을 이용하여 MST를 구한다.

## 느낀점
처음에 단순한 백트래킹인줄 알고 풀이를 시도하였으나 생각해보니 방문 노드를 재방문할 수 있는 것 같아서 MST 방식으로 풀었다.

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.10.30
풀이 시간: 120분
채점 결과: 정답
예상 문제 유형: dfs, 우선순위큐
시간: 86.81ms(최악)
메모리: 93.4MB (최악)

## 풀이방법
1. 0, 0 부터 dfs탐색을 시작하는데 상하좌우로 접근하여 높이 차이가 h보다 작은값으로 재귀해주며 높이차이가 그보다 크면 해당 위치와 높이차이를 우선순위 큐에 저장해준다.
2. 모든 dfs 탐색이 끝났다면 우선순위 큐에서 높이차이가 가장 작은 값을 꺼내준다.
3. 방문하지 않은 위치라면 answer에 높이차이를 더해주고 dfs 탐색을 시작한다.

**Comment by sangholee235** [comment]
### 풀이사항
풀이일자: 241029
풀이시간: 1시간 40분
채점결과: 정답
예상문제유형: mst


### 풀이방법
1. BFS로 영역을 나눈다
2. 영역간의 간선 및 비용을 모두 저장한다.
3. 간선을 비용으로 정렬한 뒤 MST를 계산한다.
 
### 복기
MST임은 떠올렸으나 영역 간의 간선을 둔다는 개념을 녹이는 부분이 어려웠다

**Comment by UnrequiredOne** [comment]
## 풀이 사항
풀이 일자: 2024.10.31
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: BFS
시간: 656.90ms, 22.4MB

## 풀이방법
1. BFS를 우선순위 큐로 돌린다.
2. 넣는다.
3. 뽑을때 방문처리해준다. 방문처리 되어있으면 스킵한다.

## 느낀점
간단한 문제지만 설계가 꼬이면 수정을 해야한다. 설계를 좀 잘하고싶다.
