### ISSUE TITLE
[BaekJoon] 퇴사

### ISSUE THREAD

**Issue by jongchan0109** [SSAFY12th/SSAFY_Algorithm#29]
문제 링크:https://www.acmicpc.net/problem/14501

**Comment by jongchan0109** [comment]
풀이 사항
풀이 일자: 2024.08.03
풀이 시간: 10분 00초
채점 결과: 정답
예상 문제 유형: DP

풀이 방법
처음 문제를 봤을 때 DP 유형이라고 생각을 했는데, n이 작은 것을 보고 O(2^n)으로도 충분히 시간이 초과되지 않을 것 같아서 dfs를 이용한 완전탐색으로 문제를 해결했다.

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 30분 00초
채점 결과: 정답
예상 문제 유형: DP, 백트래킹

풀이 방법
백트래킹을 통해서 가능한 모든 경우의 수를 구하고 그중 최대값을 리턴하였다.
DP를 통해서도 풀수있을거 같지만 머리가 굳어서 생각이 잘안난다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.06
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 다이나믹 프로그래밍

## 풀이 방법
1. 퇴사일로 부터 1일까지 역순으로 dp테이블 초기화
2. 현재날짜 + 현재날짜의 상담 소요일이 퇴사일을 넘어가면 -> 다음날의 dp테이블 사용
3. 현재 상담을 선택할것인지, 선택하지 않을것인지 dp테이블 비교로 초기화

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.07
풀이 시간: 2시간
채점 결과: 정답
예상 문제 유형: DP

- 풀이 방법
역순으로 읽어내면서 일자가 넘기면 컷 시켰음
이걸 DP로 풀면서 헷갈렸던 점이 2가지였음
1. 이번 회차 상담을 잡을 지 말지 선택하는것
2. 그에 따른 인덱스 선택
이 두 부분에서 잘못 판단했고 그래서 이 문제에서 시간이 많이 소요됨

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.06
풀이 시간: 30분 00초
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
 dfs를 이용한 완전탐색으로 문제를 해결했다. 싸탈마렵다.
