### ISSUE TITLE
[BaekJoon] 치킨배달

### ISSUE THREAD

**Issue by jongchan0109** [SSAFY12th/SSAFY_Algorithm#30]
문제 링크: https://www.acmicpc.net/problem/15686

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.05
풀이 시간: 35분
채점 결과: 정답
예상 문제 유형: 백트래킹

풀이 방법
백트래킹(dfs) 조합을 사용하여 m개의 치킨집을 구하고 최소 도시치킨거리를 갱신하여 문제를 해결했다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.02
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: BFS 와 DFS

## 풀이 방법
1. 치킨집을 맵에 M개 남기는 경우를 브루트포스
2. 가정집 위치와 전체 치킨집 위치를 구분하여 입력 받음
3. DFS로 M개의 치킨집 위치가 확정되면
4. BFS탐색을 통해 치킨 거리 구하기
5. 최소 치킨 거리와 비교하여 최종 거리 출력

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.03
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: DFS

## 풀이 방법
dfs를 이용한 조합(n개의 치킨 집 중 m개 선택)
m개의 치킨 집과 가정집들을 2중 for문으로 반복하면서 최소 거리 계산

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.08
풀이 시간: 16분
채점 결과: 정답
예상 문제 유형: 조합

- 풀이 방법
DFS를 이용해서 조합을 만드는 형태라고 생각을 해서, 언어 특성 상 조합을 쉽게 만들 수 있기에, 그냥 DFS를 안쓰고 조합을 만드는 방법을 선택함.
그 결과 3중 루프가 필요( 1. 조합, 2. 모든 집, 3. Sum(distance))했으나, N과 M이 그렇게 크지 않아서 유효한 풀이라고 생각했음.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.06
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
DFS 조합을 사용하여 치킨집을 m개 고르고 배열에 저장, 배열에 있는 치킨집에 모든 집을 도는 배열을 만들어서 최솟값 구하기 가장 작은 최솟값 출력 순서로 문제를 풀었다.
