### ISSUE TITLE
[BaekJoon] 링크와 스타트

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#46]
문제 주소: https://www.acmicpc.net/problem/15661

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.10
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 백트래킹

풀이방법)
1. 능력치 값을 모두 더한다. (link팀의 값으로 활용)
2. 백트래킹(조합)으로 경우의 수를 모두 탐색한다
    2.1 방문하지 않았으면 방문배열을 갱신한다.(true면 start팀)
    2.2 start팀의 값은 더하고 link팀은 값은 빼준다
    2.3 능력치 차이를 최솟값(min)과 비교해서 갱신한다.
3. min을 출력한다.

피드백)
조합이 아닌 순열 방식을 사용해서 시간초과가 발생하였다.
문제를 읽고 단순 백트래킹을 하는 것이 아닌 조합인지 순열인지를 잘 파악해야할 거 같다.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.10
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: 조합

## 풀이 방법
1. 조합을 통해서 1번 팀과 2번 팀으로 나눈다.
2. 나누어진 팀의 차이를 구해 최솟값을 갱신한다.

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 15분
채점 결과: 정답
예상 문제 유형: 조합

- 풀이 방법
1. 1명 이상이어야 한다고는 하나, 2명이상이 아니라면 점수가 아예 안나오기도 하고, N의 범위가 4이상이기에 2명을 무조건 뽑아야한다고 생각했다.
2. 조합의 특성, (nCr = nCn-r)을 이용해서 조합의 개수를 절반으로 줄였다.
3. 조합을 통해서 1번 팀을 뽑고, entry로부터 1번팀에 없는 번호들로 2번 팀으로 설정한다.
4. 최소값을 갱신한다.
5. 최대한 백트래킹에 가깝게 하기 위해, 만약 min_diff가 0으로 갱신된다면 바로 break를 하게 코드를 작성하였다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: DFS 완전 탐색

## 풀이 방법
1. 비트마스킹으로 팀을 나눈다
2. 팀이 나눠지면 팀 점수차 계산

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.07
풀이 시간: 60분
채점 결과: 정답
예상 문제 유형: dfs

풀이방법

// 2. 팀을 나누기 위한 팀 배열 선언
// 2-1. 인원수를 다르게 팀원을 분배해서 팀 배열 만들기
// 3. 팀 인원수에 따른 dfs 조합 만들기
// 4. 뽑은 팀원들의 능력치 합 구하기
// 4-3. 합의 차이 구하기
// 5. min과 비교했을때 더 작다면 min 초기화

**Comment by kub938** [comment]
# 풀이 사항
- 풀이 일자: 2024.08.14
- 풀이 시간: 90분
- 채점 결과: 정답
- 예상 문제 유형: DFS 완전 탐색

# 풀이 방법
1. 순열 조합 생성
2. a_team, b_team으로 팀을 나눔
3. 점수차 계산
4. 최소값 계산
