### ISSUE TITLE
[BaekJoon] 부등호

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#47]
문제 주소: https://www.acmicpc.net/problem/2529

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.09
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 백트래킹

풀이방법)
1.백트래킹을 돈다
2.방문하지 않고 부등호에 조건에 맞으면 계속 호출
3.n+1만큼 백트래킹이 돌면 min max 갱신
4.앞에 0이 생략되면 안되니 String으로 변환하고 길이를 계산해서 0을 붙혀줬다.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.11
풀이 시간: 13분
채점 결과: 정답
예상 문제 유형: 백트래킹

## 풀이 방법
1. 숫자의 개수는 총 10개이고, 중복이 허락하지 않는 순열이기 때문에, 시간복잡도 O(10!) = O(3628800이 된다고 생각했고, 문제 제한 시간이 1초(약 1억번의 명령어 실행)이기 때문에 완전 탐색이 가능하다고 생각해서 백트래킹을 사용했다.
2. 백트래킹을 돌면서 생긴 수열로 문제에서 입력받은 부등호 조건에 맞는지 확인한다.
3. 최댓값, 최솟값을 구해야 하는데, 백트래킹 방식이 항상 가장 작은 수부터 시작해서 가장 큰수로 탐색하므로, 최솟값의 배열이 null일 경우 clone를 해줬고, 최댓값 배열은 항상 clone를 해주었다.

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: 순열

- 풀이 방법
1. 순열을 다 만들어놓고, 부등호식을 만족하는 것들을 모두 담았다.
2. 순열 순서대로 저장되었으므로 무조건 0번째 인덱스엔 최소, 마지막 인덱스엔 최대값이 저장될 것이 자명하다 생각하였다.

순열이기때문에 sort를 생략할 수 있다 확신했고, 언어의 특성 상 순열을 만들기 쉽기때문에 그냥 만족하지 않는 순열만을 쳐내면 충분하다고 생각했다. 
비록 풀이는 순열이지만 백트래킹에 가깝게 하기 위해 중간에 쳐내는 코드도 사용하였다.
그러나 가짓수는 백트래킹에 비하면 여전히 많기 때문에, 더 효율적인 코드를 사용하기 위해 노력해야 할 것 같다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 순열 완전탐색

## 풀이 방법
1. 모든 숫자 순열을 만들어본다.
2. 해당 순열사이에 부등호를 끼워넣고 검증한다
3. 검증에 통과한다면 . 최대값, 최소값과 비교한뒤 갱신한다.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.13
풀이 시간: 만 3일
채점 결과: 정답
예상 문제 유형: DFS

풀이방법)
1. 최저값은 0부터 dfs, 최고값은 9부터 dfs
2. 조건에 맞는 최초값만 출력해준다.
