### ISSUE TITLE
[BaekJoon] 단지번호붙이기

### ISSUE THREAD

**Issue by dwshin-dev** [SSAFY12th/SSAFY_Algorithm#48]
문제 주소: https://www.acmicpc.net/problem/2667

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.08
풀이 시간: 12분
채점 결과: 정답
예상 문제 유형: DFS, BFS

풀이방법)
한번 풀었던 문제라 빠르게 로직을 파악했다.

1.맵 정보를 배열에 저장한다.
2.맵을 탐색하면서 값이 '1'이라면 해당 위치를 기반으로 dfs수행
    2-1 DFS를 수행하면서 한번 탐색한 노드가 재탐색되면 안되도록 '0'으로 변경
3. DFS가 수행된 숫자만큼 리스트에 넣음
4. 정렬 후 답 출력

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.08.10
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: BFS

잉... 마지막에 정렬해서 출력해야하는지모르고 왜 정답안되는지 반례 찾아봤습니다
(문제는 꼼꼼히 읽자 )

풀이방법은간단하다 각 영역마다 BFS를 돌면된다 !
단순히 2중포문으로 첫 1을 만났을때 큐에넣고
BFS를 돈다!
그리고 나면 다음칸에 갔을대는 dist (방문배열에) False값을 입력을 줘서 안돌게하는게 포인트...?

두서없이 썼는데 이정도만 이해해도 될것같다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.12
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: BFS 

## 풀이 방법
1. 각 단지를 돌며 BFS탐색후 0으로 바꿈 
2. SUM을 1로 시작해서 집이 하나만 있어도 단지로 취급

SUM을 0으로 시작해서 단지에 집이 하나만 있으면 단지로 취급 안하는 실수를 저지르고 말아버린 것이다.

**Comment by kub938** [comment]
## 풀이 사항
풀이 일자: 2024.08.12
풀이 시간: 45분
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. visted로 방문 확인
2. 2중포문으로 board가 1이고 방문하지 않은곳에 들어갈시 bfs를 실행해 1인곳의 갯수를 세서 리턴
3. 리턴 받은 값을 배열에 저장
4. 출력

**Comment by UnrequiredOne** [comment]
- 풀이 사항
풀이 일자: 2024.08.12
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: 조합

- 풀이 방법
 1. arr[i][j] 를 탐색하면서 1을 찾아낸다.
 2. 찾아냈다면, BFS를 시행한다.
 3. BFS를 시행하며 arr[x][y] 를 0으로 만든다. 그러면서 집의 개수를 센다
 4. 집의 개수를 저장하고, 정렬하여 출력한다.
 
매우 전형적인 BFS 문제지만, 리스트를 먼저 탐색 해야한다는 점에서 좀 비효율이 생기는 것 같다. 이것을 더 짧게 할 수 있는 방법에 대하여 고민을 해봐야겠다.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.12
풀이 시간: 12분
채점 결과: 정답
예상 문제 유형: dfs

## 풀이 방법
1. 배열을 탐색하면서 1을 발견할 시 dfs를 시작한다.
2. 현재 좌표에 대해 일정한 경로로 탐색을 하며, 방문한 좌표에는 visited 배열을 사용해 재방문 하지 않도록 한다.
3. 방문한 좌표마다 sum 값을 증가시켜 dfs가 영역의 크기를 반환하게 한다.

다들 방문한 노드의 좌표를 0으로 만드는 방식을 사용했는데, 생각해보니 이 방식이 시간적인 측면은 비슷하지만, 메모리적인 측면에서 더 효율적인 것 같다.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.14
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: DFS

풀이방법)
1.맵 정보를 배열에 저장한다. (공백 없는 문자열로 주어져서 str.charAt()으로 나눠주고 -'0' 해서 받아왔다.
2.cnt를 집의 갯수로 생각하고 1로 초기화한뒤 조건에 맞는 좌표를 dfs로 넘겨주었다.
2-1 DFS를 수행하면서 4방 탐색을 하고 조건에 맞는 주소로 다시 dfs 재귀 해준다.
3. DFS가 수행된 숫자만큼 리스트에 넣음
4. 정렬 후 답 출력
