### ISSUE TITLE
[BaekJoon] 1303 전쟁 - 전투

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#71]
문제 링크
https://www.acmicpc.net/problem/1303

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 20분
채점 결과: 정답
예상 문제 유형: DFS,BFS

풀이방법
1. 데이터를 입력받는다.
    1.1 width, height를 입력받고
    1.2 맵(배열)의 정보를 받는다
2.맵을 전부 돌면서 'B' 'W'의 집합 위력 합을 더한다.
    2.1 BFS 혹은 DFS를 통해 상하좌우에 있는 같은 팀을 찾는다.
    2.2 한번 탐색한 부분은 다시 방문하지 않도록 '0'으로 바꾼다.
3. 위력을 출력한다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 10분
채점 결과: 정답
예상 문제 유형: BFS

## 풀이 방법
단지번호 붙이기 마냥 맵에서 같은 팀을 구분하여 인원수 카운트하여 리턴하는 함수를 만듦

리턴되는 숫자 만큼 제곱하여 각 팀에 더해주면 끝

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.20
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
단지 번호 붙이기랑 똑같이 풀이했음

cnt초기화, dfs탐색, 리스트에 cnt 넣어주기

깔끔하지 못했던 풀이는 반성
1. 모여있는 군사의 수를 입력받는 리스트를 굳이 dfs에 넣어주지 않아도 되지만 처음엔 파라미터로 넣어주었다가 뺏다. 
-> 언제 계산할지를 잘 생각해서 메서드를 구성하자
2. 처음 탐색할 경우 dfs에 들어가기 전에 visited[i][j]를 빼먹었었다.
-> 방문 배열 확인은 기본적이라 생각한다. 언제 초기화해주는지 첫번째 들어갈땐 어떻게 초기화할것인지 항상 고민하자.
3. 유효한 값임을 확인하는 if문에 왜 break를 썻는지 이해가 안된다. if(nx < 0 || nx >= M || ny < 0 || ny >=N) break;
-> continue이다. 이거땜에 10분썼다. 그래도 빨리 찾아낸 편이라 생각한다. 생각하고 코드짜자. 반성하자.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.21
풀이 시간: 15분
채점 결과: 정답
예상 문제 유형: bfs

## 풀이 방법
1. 2중 반복문으로 배열을 순회한다.
2. 반복문 순회시 이전에 방문하지 않은 곳이면, bfs로 근처 탐색을 한다.
3. 넓이를 구한다.

**Comment by PyeonMinjun** [comment]
close
