### ISSUE TITLE
[swea] [SW Test 샘플문제] 프로세서 연결하기

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#72]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV4suNtaXFEDFAUf

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 100분 00초
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
1. 외각에 붙어있지 않은 core 수와 coreMap 입력받아 dfs로 core의 갯수만큼 4방향을 중복순열로 계산해주었다.
2. 방향 숫자대로 끝까지 찍기 성공했다면 간선의수 lineCnt에 더하기, coreCnt 추가해주었다.
3. 최대 core의 수보다 크다면 초기화, 정답 초기화
4. 최대 core의 수랑 같다면 간선 수 비교후 작다면 정답 초기화
5. 처음 제출했을때 테케가 시간초과나서 코드에 core를 더 탐색을 해봤자 최대 정답이 나올 수가 없는 구조라면 그냥 break 해주었고 패스가 나왔다.
if(코어의 수 - 현재까지 탐색한 코어 수 + 현재까지 연결된 코어의 수 <  이전 최대 연결된 코어의 수)

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 부분 집합

풀이 방법)
1.데이터 입력받기
2. 부분집합으로 코어 집합을 추출
    2-1. 추출한 집합에 대해서 각 값을 전선 방향에 대해서 DFS 실행
        2-1-0 선을 긋고 다음 dfs를 호출하고 그은 선을 원상복귀한다.
        2-1-1. 코어 개수가 크면 coremax와 lineMin 갱신
        2-1-2. 코어 개수가 같다면 전선길이가 더 짧으면 lineMin 갱신

피드백)
다른 코드들을 보니 내 코드에 비해서 실행시간이 굉장히 짧게 나왔다.(1122 >>>>>> 250)
아예 부분집합으로 집합을 추출할때, 선을 그으면서 체크를 하면 시간을 확 줄일 수 있는 거 같다.
다음에는 이러한 부분도 신경쓰면서 시간을 최대한 짧게 해야할 거 같다.
또한 문제 풀기전 시간복잡도를 계산하는 것도 필요해보인다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 조합 DFS

## 풀이 방법
깔릴 수 있는 모든 전선의 경우의 수를 조합하여 
최대 코어의 개수 - 최소 전선의 길이 우선순위로 갱신. 끝

일반적인 visited 배열로 구분하는 문제와 달리

전선을 다 깔고 난뒤, DFS를 탈출하면 
전선을 다시 회수 하는 부분에서 차이가 있음

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.18
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: 백트래킹

## 풀이 방법
1. 조합을 통해 core를 선택한다.
2. core에서 연결할 수 있는 4방향을 탐색한다.

### 느낀점
크게 어렵지는 않은 문제이지만, 전선을 설치하고, 설치한 전선의 수를 반환하고, 다시 전선을 제거하는? 함수를 한개로 구현을 하여 재미있게 설계한 것 같다. 모든 core를 고려하지 않고, 가장자리에 없는 core만 조합으로 선택하여 시간을 줄일 수 있었다.

**Comment by UnrequiredOne** [comment]
### 풀이 사항
---
풀이 일자: 2024.08.22
풀이 시간: 100분
채점 결과: 정답
예상 문제 유형: DFS를 이용한 부분집합

### 풀이 방법
---
1. 벽에 붙어 있는 코어 숫자를 세고, 벽에 붙어있지 않은 코어 위치를 저장한다
2. 벽에 붙지있지 않은 core에서 연결할 수 있는 4방향을 탐색한다.
3. 뻗는게 가능한 경우의 수를 저장한다. 만약 없다면 그 코어를 remove 해버린다.
4. 전선을 깔고 전선의 위치를 임시 스택에 저장한다. 만약 다른 전선이 있다면, 취소한다.
5. 다음 인덱스를 탐색한다.
6. 빠져나오면 임시 스택을 이용해 전선을 회수한다(4~6번을 백트래킹의 형태처럼 구현함)


### 느낀점
---
문제 설계 자체는 그렇게 어렵지 않았지만, 코드를 작성하는데 실수가 많아서 오류를 고치는데 시간을 너무 많이 썼다.
결정적인 실수는 전선의 위치를 저장한 stack의 위치였으며, 변수를 둠에 있어서 위치를 고려하는 것을 명심해야할 것이다.
