### ISSUE TITLE
[Swea] [모의 SW 역량테스트] 보호 필름

### ISSUE THREAD

**Issue by leafeafeaf** [SSAFY12th/SSAFY_Algorithm#73]
문제 링크
https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV5V1SYKAaUDFAWu

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.16
풀이 시간: 50분
채점 결과: 정답
예상 문제 유형: 부분 집합
풀이 방법)
1. 데이터를 입력받는다.
2. 부분집합 함수를 돌면서 최솟값을 갱신한다.
    2.1 먼저 통과기준에 맞는다면 최솟값을 갱신한다.(기저조건 1)
    2.2 모든 막을 변경하였으면 종료한다.(기저조건 2)
    2.3 해당 막을 가만히 두는 경우, A로 변경하는 경우, B로 변경하는 경우로 나누어 재귀 호출한다.
    2.4 현재 최솟값보다 막을 변경하는 개수가 많은 경우는 더 재귀를 호출할 필요가 없다(백트래킹, 가지치기)
3. 최솟값을 출력한다.

가지치기 없이 부분집합으로만 구성하니 시간 초과가 발생하여 꽤나 까다로웠다.
가지치기를 통해서 탐색할 필요가 없는 경우의 수를 생각하는 것이 중요하다는 걸 느꼈다.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.17
풀이 시간: 15분
채점 결과: 정답
예상 문제 유형: 백트래킹

## 풀이 방법
1. 조합을 통해 1또는 0으로 바꿀 행을 선택한다.
2. 주어진 조건을 맞는지 확인하고, 맞다면 최솟값을 갱신한다.

### 느낀점
크게 어렵지 않은 문제라고 생각하여 시간복잡도를 분석하지 않았고, 시간 초과가 발생하였다.
k개의 숫자들이 연속해서 동일하면 문제의 조건을 만족한다. 이는 k개 이상의 숫자를 변경 하였으면, 재귀함수를 종료하라는 의미인데, 이를 생각하지 못했다.

**Comment by UnrequiredOne** [comment]
### 풀이 사항
---
풀이 일자: 2024.08.21
풀이 시간: 100분
채점 결과: 정답
예상 문제 유형: 조합

### 풀이 방법
---
K > 1일때만 시행하도록 했다.
약품 시행 횟수 cnt를 두고, 이걸 기반으로  조합을 통해 바꿀 행들을 선택한다.
그리고 cnt 길이만큼의 이진수를 생각해서 0, 1의 조합으로 행의 투입할 약품을 선택하였다.
주어진 조건을 맞는지 확인하고, 맞다면 break를 하였다.

### 느낀점
---
이걸 풀면서 저지른 실수 목록은 다음과 같다.
1. 시간복잡도 생각안하고, 체크를 슬라이딩 윈도우로 해버린것
2. Try 횟수에 한계가 있다고 생각을 안해서 무한루프나 array index 에러를 만든것
3. D와 W를 헷갈린것
문제가 크게 어렵지 않고 조금 자세히만 읽으면서 따라오면 풀 수 있는 문제인데, 조금만 어려워져도 실수를 너무 많이하는 것 같다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.21
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: 조합 DFS

## 풀이 방법
백트래킹을 통한 최소 약품 투입 횟수 탐색

dfs 메소드를 통해 각 막을 변경하지 않거나, A 또는 B로 변경해가면서 모든 가능한 조합을 탐색
각 조합에 대해 성능 검사를 통과할 수 있는지 확인하고, 최소 약품 투입 횟수를 갱신

각 세로 열에 대해 동일한 특성의 셀이 K개 이상 연속적으로 있는지 검사
모든 열이 통과하면 true를 반환하여 해당 조합이 합격 기준을 충족함을 검증

**Comment by PyeonMinjun** [comment]
close
