### ISSUE TITLE
[BOJ] Puyo Puyo

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#92]
문제링크:
https://www.acmicpc.net/problem/11559

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.25
풀이 시간: 30분
채점 결과: 정답
예상 문제 유형: DFS

풀이 방법
1. 데이터를 입력 받는다. 12줄의 char[][]
2. 연쇄가 발생하지 않을 때까지 3,4,5를 반복
3. 바닥 칸부터 .이 아닌 모든 칸에 대해서 dfs를 돌린다.
     3.1 칸을 '?'로 설정하고 dfs 호출 횟수를 증가 시킨다.
     3.2 상하좌우의 자신과 같은 알파벳이면 dfs호출
4. dfs호출횟수가 4회 이상이면 '?'를 '.'으로 바꾸고 아니면 원상 복구시킨다
5. 모든 블럭을 아래로 떨어트린다

처음에는 개수를 세고 값을 바꾸는것을 하나의 dfs로 구현했지만
dfs 특징에 대해 잘 생각하지 못해서 값이 정상적으로 갱신되지 않는 문제가 있었다.
나같은 경우, 개수파악 dfs, 값 갱신하는dfs 두개를 사용했지만 다른 답안을 찾아보니
dfs하나만 사용해서 list에 바꿀 좌표를 저장하고 for문으로 한번에 바꾸는게 더 직관적인 구현방식인 거 같다.

**Comment by UnrequiredOne** [comment]
### 풀이사항
---
- 풀이 일자: 2024.08.27
- 풀이 시간: 30분
- 채점 결과: 정답
- 예상 문제 유형 : BFS

### 풀이 방법
---
1. 72칸을 다 돌면서 '.'가 아닌걸 찾는다.
2. BFS를 돌린다. 
3. 만약 동일한 색상의 뿌요가 4개 이상이면, 터뜨린다. 체인은 터트린 횟수가 아닌, 터짐이 발생하는 화면의 갯수이므로 유의하자.
4. 바닥으로 떨어뜨리자.
5. 만약 탐색했을때 터뜨림이 없다면, break

실수만 하지 않는다면 무난하게 풀리는 문제같다.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 100분
채점 결과: 정답
예상 문제 유형: DFS, BFS, 구현

풀이 방법
맵에서 이어져있는 같은 값인 요소를 골라서 4개이상이면 맵에서 지우고 밑으로 내리게 하는 인접 탐색과 구현을 같이 물어보는 문제였다. 

1. 맵을 입력받고 지워야되는 원소 저장할 배열을 선언해주었다. 최대크기가 맵의 사이즈이므로 72개

2. 더이상 맵이 바뀌지 않을 때까지 반복하기 위해 while문 안에서 맵을 돌며 비어있지 않은 값이 들어있는 곳에 도착하면 주변에 몇개까지 이어져있는지 dfs를 돌며 확인해준다.

3. 4개 이상 이어져 있다면 arr 배열에 저장해둔 위치로 가서 맵에서 해당 값을 삭제해 준다.

4. 다 돌았는데 바뀐적이 없다면 break;

5. 빈공간이 생겼으면 아래로 떨어지게 만든다. 스택을 사용해서 위쪽에서부터 값이 들어있다면 삽입해주고 맵의 값을 지워준다. 끝까지 도착했다면 다시 맨밑에서 부터 꺼내준다. 만약 반대로 뒤집어서 넣어주고 싶다면 스택이 아니라 큐를 사용하면 될것같다.

6. ans증가시키고 2~5를 반복해준다.

 for문에서 cnt의 범위를 잘못지정하는 실수때문에 오래걸리게 되었다. 조심하자.

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 25분
채점 결과: 정답
예상 문제 유형: 구현, DFS, BFS

## 풀이 방법
1. 2차원 반목문을 순회하면서 '.' 가 아닌 좌표 발견 시 탐색 시작
2. BFS로 탐색하면서 범위 안에서 방문한 적 없고 같은 문자인 경우 queue에 담는다.
3. queue에서 나온 좌표들을 다시 remove큐에 담아서 삭제할 것을 구현한다.
4. remove큐의 크기가 4이상인 경우 좌표의 값을 '.'로 바꾼다.
5. 보드가 move되는 것을 구현하는데 List를 이용하여 편하게 구현한다.

### 느낀점
문제를 제대로 읽지 않아서 음 전체 뿌요 된? 경우를 카운트 했는데 그게 아니었다..

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 구현

## 풀이 방법
1. 방문한적이 없는 뿌요를 만나면 뿌요 끼리 연결 되어있는지 확인
2. 4개 이상 연결 되어있다면, 터트려
3. 터트린 후 중력 업데이트

### 느낀점
중력부터 하고 뿌요 하려 했는데 그러면 카운트가 제대로 안올랐음
