### ISSUE TITLE
[BOJ] 감시

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#93]
문제링크:
https://www.acmicpc.net/problem/15683

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by leafeafeaf** [comment]
풀이 사항
풀이 일자: 2024.08.26
풀이 시간: 1시간 10분
채점 결과: 정답
예상 문제 유형: 중복 순열

풀이방법
1. 데이터를 입력받는다.
 1-1 cctv의 정보를 저장하는 리스트를 생성하고 저장한다.
2. 각 cctv에 대해서 방향을 중복순열로 구한다
3. 중복 순열이 끝나면 타입에 따라서 선(방문)을 긋고 개수를 파악해서 최댓값을 구한다

5번 cctv나 2번 cctv같은 경우는 회전이 의미 없는 경우가 생기므로 해당 경우를 돌지 않도록 구현하였다.

느낀 점)
로직자체는 빠르게 파악했으나 구현과정에서 미흡한 부분이 많았다.
잦은 실수를 방지하기 위해서 처음 짤때 막짜지말고 설계에 따라서 차근차근 작성해야할 거 같다.
또한 -1 % 4 는 -3이라는걸 파악하지 못해서 시간이 많이 지연 되었다. 이 부분도 확실하게 기억해야 할 거 같다.

**Comment by PyeonMinjun** [comment]
풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 3h
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현 / 4진법 (비트마스킹...?)

풀이 방법
- cctv 방향설정
-정한 바라보는 방향에 대한 사각지대 구하기 !

1. upd 함수
감시카메라가 바라보는방향을 7로 만드는 함수

2. 4진법을 활용해서 모든 부분집합의 총개수를 만들고,  사각지대 최소개수 갱신

바라보는 CCTV의 방향은 4방향이므로 총 4^(N)-1 
해당 부분집합의의 사각지대 최소 개수를 갱신! 


_mind_ 
cctv 방향 정하기.

예를 들어 1번 카메라가 2개있다면, 
방향이 `(북,북)`  (북, 동) ( 동, 북) 도 가능하고  16개의 가능성이 있다.
각각의 배치들에 대해 사각지대의 갯수를 센 후 그 중 최솟값을 찾기.
방향을 정하는건 N과 M(3)문제와 판박이라 `백트래킹`을 이용하면 된다.

하지만 지금의 상황과 같이 변수들이 가질 수 있는 값이 여러개이고 모든 조합을 다 확인해보고 싶은데 변수들끼리는 서로 독립적일 땐 백트래킹을 쓰는 대신 더 쉬운 방법이 있다

가능한 방향의 종류가 4개 4진법
1번카메라가 3개 일때 0부터 ~ 63까지의 수를 4진법으로 표현
- 0~ 63 자릿수를 4진수로 표현하고 각 자릿수를 얻는 방식으로 코드를 짜야함.
각각의 자리를 방향 3개에 대응
중간에 `39`이면 4진수로 213이니까 방향을 (2,1,3)으로 둘 수 있다.
이렇게하면 모든 가능한 모든 64가지의 모든 조합을 확인해 볼 수 있다.

사각지대 개수구하는건 어떻게든 구현하면됩니다.

성민이말대로 5번 cctv경우 표현할 필요가없는데 예외처리를 안해줌으로써 코드를 깔끔하게 작성해봤습니다.
( 많이 참고함 )

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 브루트포스

## 풀이 방법
1. 시간 제한은 1초이고, N과 M이 매우 작기 때문에 브루트포스 알고리즘을 사용하여 풀어야겠다고 생각했다.
2. cctv를 모두 입력받아 리스트에 저장하고, 그 길이 만큼 중복 순열을 생산하여 구현했다.


### 느낀점
현재 시간이 500ms가 나왔는데, 시간을 줄일 방법을 생각해보았다.
1. cctv가 5번 유형인 경우, 중복순열로 방향을 정하지 않아도 된다.
2. watch를 구현했을 때 바꾼 수 만큼 값을 누적하여 계산한다.

코드의 리펙토링이 적용이 되지 않아서 코드가 조금 길고, 난해한데 시간이 나면 리펙토링 해봐야겠다...

**Comment by UnrequiredOne** [comment]
### 풀이 사항
---
풀이 일자: 2024.08.28
풀이 시간: 80분
채점 결과: 정답
예상 문제 유형: 중복 순열

### 풀이 방법
---
1. CCTV의 갯수 K 가 8 까지이므로 순열을 써도 세이프라고 생각했음
2. 그럼 중복 순열을 어떻게 구현하냐를 고민하다가 4진법을 사용하기로 함.
3. 그래서 5번 유형의 카메라를 따로 저장해서 먼저 설치한 다음,
4. 거기서 한번 answer를 갱신하고 다른 유형의 카메라를 순열의 값에 따라 설치함.

### 느낀점
---
날이 갈수록 실수가 늘어가는 것만 같아서 슬픔.
처음에 왜 답이 계속 틀린지 고민하다가 answer을 카메라 집합(5번인것, 5번이 아닌것)마다 갱신해줘야하는데 후자에서만 했던것임.

또한 N이나 M이 1이어도 벽을 뚫을수 없는 것을 생각 안하고 N or M이 1이면 그냥 0 처리 했던 코드 역시 문제였음

계속 신중하게 작성해야한다 반성하면서 전혀 진화를 못하고 있음..... 매우 슬픔

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.27
풀이 시간: 40분
채점 결과: 정답
예상 문제 유형: 중복순열

## 풀이 방법
1. 씨씨티비 별로 회전 될 수 있는 모든 경우의 수를 조합
2. 조합 된 경우로 씨씨티비가 볼 수 있는  부분을 색칠
3. 색칠 되지 않은 부분 카운트

**Comment by dwshin-dev** [comment]
## 풀이 사항
풀이 일자: 2024.08.29
풀이 시간: 40분 00초
채점 결과: 정답
예상 문제 유형: DFS, BFS

## 풀이 방법
1. CCTV의 최대 개수가 8개를 넘지 않고 사무실의 크기 또한 64를 넘지 않았기 때문에 완전탐색으로 문제를 풀 수 있을것이라고 생각하고 DFS의 중복순열을 통해 CCTV감시 방향을 정해주엇다.

2. CCTV 5의 경우에는 어떤상황에서도 4방을 감시하기 때문에 CCTV 배열을 따로 관리해주고 맵에 감시 범위를 미리 채운 뒤 DFS탐색에 포함시키지 않았다 .
3. 각 CCTV의 종류마다 감시범위를 다르게 설정해서 BFS에 좌표와 방향을 파라미터로 넘겨주어 맵을 채워주었고 다 끝났다면 ans와 비교해서 최소값을 출력해준다.

## 느낀점
맵을 채우는 BFS과정에서 0일때만 맵을 채워주고 큐에 좌표를 넣어줬는데 이렇게 하면 감시범위가 겹치는 경우에 그 뒤까지 더이상 탐색을 진행하지 않아 오답이 나오게 되었다. 따라서 벽이 아닌경우에는 무조건 채우고 벽으로 채우는게 아닌 다른 값으로 채워주었다. CCTV의 좌표는 이미 가지고 있으므로 맵에서 CCTV가 사라지는것을 두려워하지 않아도 된다.
