### ISSUE TITLE
[BOJ] 소문난칠공주

### ISSUE THREAD

**Issue by PyeonMinjun** [SSAFY12th/SSAFY_Algorithm#94]
문제링크
https://www.acmicpc.net/problem/1941

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by jongchan0109** [comment]
## 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 34분
채점 결과: 정답
예상 문제 유형: 조합, 백트래킹, 브루트포스

## 풀이 방법
1. 시간 제한은 2초이고, N은 5이므로, 브루트포스 알고리즘을 사용해도 될 것이라고 판단했다.
2. 우선 조합을 이용해 7개의 원소를 뽑았다
3. 7개의 원소에서 S의 개수를 계산하여 4미만인 경우 인접 여부를 확인하지 않았다.
4. dfs를 사용하여 인접 여부를 확인하였다.

### 느낀점
문제의 조건과 시간 복잡도를 계산해보면, 어떤 방식으로 풀어야 할 지 대강 나오는 것 같다.

**Comment by dwshin-dev** [comment]
풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 120분
채점 결과: 정답
예상 문제 유형: DFS, BFS

풀이 방법
처음에 DFS로 풀이했다가 모양이 T자 이거나 E자인 경우는 DFS로 계산하기 힘들어서 부분집합으로 원소가 7개이고 임도연이 4개 이하로 속하는 모든 집합을 구해서 그 집합들의 모든 원소가 이어져있는지 BFS를 통해 계산하였다.

1. 맵을 입력받고 dfs를 통해 부분집합을 구해준다. dfs의 파라미터로는 임도연의 수, 조합을 짜야하므로 원소가 시작하는 부분인 at, 크기 depth로 주었다.

2. 맵이 5 x 5 = 25이므로 원소를 0부터 24까지 배열에 넣어준다. 기저조건으로는 임도연이 4개 이상이면 바로 return, 원소가 7개 모두 채워졌으면 bfs탐색을 하고 return

3. map을 만들어서 첫번째 원소를 제외한 나머지 원소들을 2차원 배열로 바꿔서 map값을 1로 넣어준다.

4. 첫번째 원소를 큐에 넣고 인접 탐색을 통해서 map값이 1인 경우만 다음 큐에 넣어주고 cnt를 증가 시켜주었다.

5. cnt가 7인 경우 모든 원소를 방문했다는 뜻이므로 모든 원소가 인접해있다는 뜻이다. 따라서 ans을 증가시켜준다.

실수1: 조합짤때 자주하는 실수인 at + 1값을 dfs에 넣어주는 실수를 하였다. at은 시작값이고 i + 1를 넣어줘야하는데 급하게 코드 짜지 말자.

**Comment by UnrequiredOne** [comment]
### 풀이 사항
---
풀이 일자: 2024.08.28
풀이 시간: 100분
채점 결과: 정답
예상 문제 유형: 조합

### 풀이 방법
---
1. 25개의 좌표에서 7개를 뽑는 조합 시행
2. 7개가 연결되어있는지 확인
3. S가 4개 있는지 확인

계속 고민을 하다가 더 나은 방법을 찾지 못하겠기에 마지막엔 결국 모든 조합을 시행했다.
설계 단계에서 시간복잡도에 대해서 생각해보는 것을 연습해봐야하는건가 고민이 매우 된다.

**Comment by leafeafeaf** [comment]
git commit -m "김성민 / 240828 / [BOJ_소문난 칠공주_1941] / 324ms"
풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 1시간 30분
채점 결과: 정답
예상 문제 유형: 조합, bfs

풀이방법
1. 데이터를 입력받는다.
2. 조합을 사용하여 좌표 7개를 선택한다
    2-1 원활한 조합을 위해 2차원좌표를 0-24로 표시
    2-2 중간에 Y의 개수가 4개를 넘어가면 백트래킹
3. 선택된 좌표가 인접해있는지 BFS를 사용하여 검사한다.

피드백)
처음 로직을 파악하기에 시간이 오래걸렸고 중간에 오타가 발생해서 디버깅하느라 시간이 너무 오래걸렸다.

**Comment by sangholee235** [comment]
## 풀이 사항
풀이 일자: 2024.08.28
풀이 시간: 1시간
채점 결과: 정답
예상 문제 유형: 조합, BFS

## 풀이 방법
1. 25개 중에 7개 무작위 선택
2. 임도연파 4명 되면 가지치기
3. 7개가 선택 된다면, 선택된 7개가 연결 되어있는지 검증
4. 검증되면 answer ++
